/* Generated by make-libxfce4panel-alias.pl. Do not edit this file. */

#ifdef HAVE_GNUC_VISIBILITY

#include <glib.h>

#undef IN_HEADER
#define IN_HEADER(x) 1

#undef IN_SOURCE
#define IN_SOURCE defined

#if IN_HEADER(__LIBXFCE4PANEL_CONFIG_H__)
#if IN_SOURCE(__LIBXFCE4PANEL_CONFIG_C__)
#undef libxfce4panel_check_version 
extern __typeof (libxfce4panel_check_version) libxfce4panel_check_version __attribute((alias("IA__libxfce4panel_check_version"), visibility("default")));

#undef libxfce4panel_major_version 
extern __typeof (libxfce4panel_major_version) libxfce4panel_major_version __attribute((alias("IA__libxfce4panel_major_version"), visibility("default")));

#undef libxfce4panel_micro_version 
extern __typeof (libxfce4panel_micro_version) libxfce4panel_micro_version __attribute((alias("IA__libxfce4panel_micro_version"), visibility("default")));

#undef libxfce4panel_minor_version 
extern __typeof (libxfce4panel_minor_version) libxfce4panel_minor_version __attribute((alias("IA__libxfce4panel_minor_version"), visibility("default")));

#endif
#endif
#if IN_HEADER(__LIBXFCE4PANEL_ENUM_TYPES_H__)
#if IN_SOURCE(__LIBXFCE4PANEL_ENUM_TYPES_C__)
#undef xfce_screen_position_get_type 
extern __typeof (xfce_screen_position_get_type) xfce_screen_position_get_type __attribute((alias("IA__xfce_screen_position_get_type"), visibility("default")));

#undef xfce_panel_plugin_mode_get_type 
extern __typeof (xfce_panel_plugin_mode_get_type) xfce_panel_plugin_mode_get_type __attribute((alias("IA__xfce_panel_plugin_mode_get_type"), visibility("default")));

#endif
#endif
#if IN_HEADER(__XFCE_ARROW_BUTTON_H__)
#if IN_SOURCE(__XFCE_ARROW_BUTTON_C__)
#undef xfce_arrow_button_get_type 
extern __typeof (xfce_arrow_button_get_type) xfce_arrow_button_get_type __attribute((alias("IA__xfce_arrow_button_get_type"), visibility("default")));

#undef xfce_arrow_button_new 
extern __typeof (xfce_arrow_button_new) xfce_arrow_button_new __attribute((alias("IA__xfce_arrow_button_new"), visibility("default")));

#undef xfce_arrow_button_get_arrow_type 
extern __typeof (xfce_arrow_button_get_arrow_type) xfce_arrow_button_get_arrow_type __attribute((alias("IA__xfce_arrow_button_get_arrow_type"), visibility("default")));

#undef xfce_arrow_button_set_arrow_type 
extern __typeof (xfce_arrow_button_set_arrow_type) xfce_arrow_button_set_arrow_type __attribute((alias("IA__xfce_arrow_button_set_arrow_type"), visibility("default")));

#undef xfce_arrow_button_get_blinking 
extern __typeof (xfce_arrow_button_get_blinking) xfce_arrow_button_get_blinking __attribute((alias("IA__xfce_arrow_button_get_blinking"), visibility("default")));

#undef xfce_arrow_button_set_blinking 
extern __typeof (xfce_arrow_button_set_blinking) xfce_arrow_button_set_blinking __attribute((alias("IA__xfce_arrow_button_set_blinking"), visibility("default")));

#endif
#endif
#if IN_HEADER(__XFCE_HVBOX_H__)
#if IN_SOURCE(__XFCE_HVBOX_C__)
#undef xfce_hvbox_get_type 
extern __typeof (xfce_hvbox_get_type) xfce_hvbox_get_type __attribute((alias("IA__xfce_hvbox_get_type"), visibility("default")));

#undef xfce_hvbox_new 
extern __typeof (xfce_hvbox_new) xfce_hvbox_new __attribute((alias("IA__xfce_hvbox_new"), visibility("default")));

#undef xfce_hvbox_set_orientation 
extern __typeof (xfce_hvbox_set_orientation) xfce_hvbox_set_orientation __attribute((alias("IA__xfce_hvbox_set_orientation"), visibility("default")));

#undef xfce_hvbox_get_orientation 
extern __typeof (xfce_hvbox_get_orientation) xfce_hvbox_get_orientation __attribute((alias("IA__xfce_hvbox_get_orientation"), visibility("default")));

#endif
#endif
#if IN_HEADER(__XFCE_PANEL_CONVENIENCE_H__)
#if IN_SOURCE(__XFCE_PANEL_CONVENIENCE_C__)
#undef xfce_panel_create_button 
extern __typeof (xfce_panel_create_button) xfce_panel_create_button __attribute((alias("IA__xfce_panel_create_button"), visibility("default")));

#undef xfce_panel_create_toggle_button 
extern __typeof (xfce_panel_create_toggle_button) xfce_panel_create_toggle_button __attribute((alias("IA__xfce_panel_create_toggle_button"), visibility("default")));

#undef xfce_panel_get_channel_name 
extern __typeof (xfce_panel_get_channel_name) xfce_panel_get_channel_name __attribute((alias("IA__xfce_panel_get_channel_name"), visibility("default")));

#undef xfce_panel_pixbuf_from_source 
extern __typeof (xfce_panel_pixbuf_from_source) xfce_panel_pixbuf_from_source __attribute((alias("IA__xfce_panel_pixbuf_from_source"), visibility("default")));

#undef xfce_panel_pixbuf_from_source_at_size 
extern __typeof (xfce_panel_pixbuf_from_source_at_size) xfce_panel_pixbuf_from_source_at_size __attribute((alias("IA__xfce_panel_pixbuf_from_source_at_size"), visibility("default")));

#endif
#endif
#if IN_HEADER(__XFCE_PANEL_IMAGE_H__)
#if IN_SOURCE(__XFCE_PANEL_IMAGE_C__)
#undef xfce_panel_image_get_type 
extern __typeof (xfce_panel_image_get_type) xfce_panel_image_get_type __attribute((alias("IA__xfce_panel_image_get_type"), visibility("default")));

#undef xfce_panel_image_new 
extern __typeof (xfce_panel_image_new) xfce_panel_image_new __attribute((alias("IA__xfce_panel_image_new"), visibility("default")));

#undef xfce_panel_image_new_from_pixbuf 
extern __typeof (xfce_panel_image_new_from_pixbuf) xfce_panel_image_new_from_pixbuf __attribute((alias("IA__xfce_panel_image_new_from_pixbuf"), visibility("default")));

#undef xfce_panel_image_new_from_source 
extern __typeof (xfce_panel_image_new_from_source) xfce_panel_image_new_from_source __attribute((alias("IA__xfce_panel_image_new_from_source"), visibility("default")));

#undef xfce_panel_image_set_from_pixbuf 
extern __typeof (xfce_panel_image_set_from_pixbuf) xfce_panel_image_set_from_pixbuf __attribute((alias("IA__xfce_panel_image_set_from_pixbuf"), visibility("default")));

#undef xfce_panel_image_set_from_source 
extern __typeof (xfce_panel_image_set_from_source) xfce_panel_image_set_from_source __attribute((alias("IA__xfce_panel_image_set_from_source"), visibility("default")));

#undef xfce_panel_image_set_size 
extern __typeof (xfce_panel_image_set_size) xfce_panel_image_set_size __attribute((alias("IA__xfce_panel_image_set_size"), visibility("default")));

#undef xfce_panel_image_get_size 
extern __typeof (xfce_panel_image_get_size) xfce_panel_image_get_size __attribute((alias("IA__xfce_panel_image_get_size"), visibility("default")));

#undef xfce_panel_image_clear 
extern __typeof (xfce_panel_image_clear) xfce_panel_image_clear __attribute((alias("IA__xfce_panel_image_clear"), visibility("default")));

#endif
#endif
#if IN_HEADER(__XFCE_PANEL_PLUGIN_H__)
#if IN_SOURCE(__XFCE_PANEL_PLUGIN_C__)
#undef xfce_panel_plugin_get_type 
extern __typeof (xfce_panel_plugin_get_type) xfce_panel_plugin_get_type __attribute((alias("IA__xfce_panel_plugin_get_type"), visibility("default")));

#undef xfce_panel_plugin_get_name 
extern __typeof (xfce_panel_plugin_get_name) xfce_panel_plugin_get_name __attribute((alias("IA__xfce_panel_plugin_get_name"), visibility("default")));

#undef xfce_panel_plugin_get_display_name 
extern __typeof (xfce_panel_plugin_get_display_name) xfce_panel_plugin_get_display_name __attribute((alias("IA__xfce_panel_plugin_get_display_name"), visibility("default")));

#undef xfce_panel_plugin_get_comment 
extern __typeof (xfce_panel_plugin_get_comment) xfce_panel_plugin_get_comment __attribute((alias("IA__xfce_panel_plugin_get_comment"), visibility("default")));

#undef xfce_panel_plugin_get_unique_id 
extern __typeof (xfce_panel_plugin_get_unique_id) xfce_panel_plugin_get_unique_id __attribute((alias("IA__xfce_panel_plugin_get_unique_id"), visibility("default")));

#undef xfce_panel_plugin_get_property_base 
extern __typeof (xfce_panel_plugin_get_property_base) xfce_panel_plugin_get_property_base __attribute((alias("IA__xfce_panel_plugin_get_property_base"), visibility("default")));

#undef xfce_panel_plugin_get_arguments 
extern __typeof (xfce_panel_plugin_get_arguments) xfce_panel_plugin_get_arguments __attribute((alias("IA__xfce_panel_plugin_get_arguments"), visibility("default")));

#undef xfce_panel_plugin_get_size 
extern __typeof (xfce_panel_plugin_get_size) xfce_panel_plugin_get_size __attribute((alias("IA__xfce_panel_plugin_get_size"), visibility("default")));

#undef xfce_panel_plugin_get_small 
extern __typeof (xfce_panel_plugin_get_small) xfce_panel_plugin_get_small __attribute((alias("IA__xfce_panel_plugin_get_small"), visibility("default")));

#undef xfce_panel_plugin_get_expand 
extern __typeof (xfce_panel_plugin_get_expand) xfce_panel_plugin_get_expand __attribute((alias("IA__xfce_panel_plugin_get_expand"), visibility("default")));

#undef xfce_panel_plugin_set_expand 
extern __typeof (xfce_panel_plugin_set_expand) xfce_panel_plugin_set_expand __attribute((alias("IA__xfce_panel_plugin_set_expand"), visibility("default")));

#undef xfce_panel_plugin_get_shrink 
extern __typeof (xfce_panel_plugin_get_shrink) xfce_panel_plugin_get_shrink __attribute((alias("IA__xfce_panel_plugin_get_shrink"), visibility("default")));

#undef xfce_panel_plugin_set_shrink 
extern __typeof (xfce_panel_plugin_set_shrink) xfce_panel_plugin_set_shrink __attribute((alias("IA__xfce_panel_plugin_set_shrink"), visibility("default")));

#undef xfce_panel_plugin_set_small 
extern __typeof (xfce_panel_plugin_set_small) xfce_panel_plugin_set_small __attribute((alias("IA__xfce_panel_plugin_set_small"), visibility("default")));

#undef xfce_panel_plugin_get_locked 
extern __typeof (xfce_panel_plugin_get_locked) xfce_panel_plugin_get_locked __attribute((alias("IA__xfce_panel_plugin_get_locked"), visibility("default")));

#undef xfce_panel_plugin_get_orientation 
extern __typeof (xfce_panel_plugin_get_orientation) xfce_panel_plugin_get_orientation __attribute((alias("IA__xfce_panel_plugin_get_orientation"), visibility("default")));

#undef xfce_panel_plugin_get_mode 
extern __typeof (xfce_panel_plugin_get_mode) xfce_panel_plugin_get_mode __attribute((alias("IA__xfce_panel_plugin_get_mode"), visibility("default")));

#undef xfce_panel_plugin_get_nrows 
extern __typeof (xfce_panel_plugin_get_nrows) xfce_panel_plugin_get_nrows __attribute((alias("IA__xfce_panel_plugin_get_nrows"), visibility("default")));

#undef xfce_panel_plugin_get_screen_position 
extern __typeof (xfce_panel_plugin_get_screen_position) xfce_panel_plugin_get_screen_position __attribute((alias("IA__xfce_panel_plugin_get_screen_position"), visibility("default")));

#undef xfce_panel_plugin_take_window 
extern __typeof (xfce_panel_plugin_take_window) xfce_panel_plugin_take_window __attribute((alias("IA__xfce_panel_plugin_take_window"), visibility("default")));

#undef xfce_panel_plugin_add_action_widget 
extern __typeof (xfce_panel_plugin_add_action_widget) xfce_panel_plugin_add_action_widget __attribute((alias("IA__xfce_panel_plugin_add_action_widget"), visibility("default")));

#undef xfce_panel_plugin_menu_insert_item 
extern __typeof (xfce_panel_plugin_menu_insert_item) xfce_panel_plugin_menu_insert_item __attribute((alias("IA__xfce_panel_plugin_menu_insert_item"), visibility("default")));

#undef xfce_panel_plugin_menu_show_configure 
extern __typeof (xfce_panel_plugin_menu_show_configure) xfce_panel_plugin_menu_show_configure __attribute((alias("IA__xfce_panel_plugin_menu_show_configure"), visibility("default")));

#undef xfce_panel_plugin_menu_show_about 
extern __typeof (xfce_panel_plugin_menu_show_about) xfce_panel_plugin_menu_show_about __attribute((alias("IA__xfce_panel_plugin_menu_show_about"), visibility("default")));

#undef xfce_panel_plugin_block_menu 
extern __typeof (xfce_panel_plugin_block_menu) xfce_panel_plugin_block_menu __attribute((alias("IA__xfce_panel_plugin_block_menu"), visibility("default")));

#undef xfce_panel_plugin_unblock_menu 
extern __typeof (xfce_panel_plugin_unblock_menu) xfce_panel_plugin_unblock_menu __attribute((alias("IA__xfce_panel_plugin_unblock_menu"), visibility("default")));

#undef xfce_panel_plugin_register_menu 
extern __typeof (xfce_panel_plugin_register_menu) xfce_panel_plugin_register_menu __attribute((alias("IA__xfce_panel_plugin_register_menu"), visibility("default")));

#undef xfce_panel_plugin_arrow_type 
extern __typeof (xfce_panel_plugin_arrow_type) xfce_panel_plugin_arrow_type __attribute((alias("IA__xfce_panel_plugin_arrow_type"), visibility("default")));

#undef xfce_panel_plugin_remove 
extern __typeof (xfce_panel_plugin_remove) xfce_panel_plugin_remove __attribute((alias("IA__xfce_panel_plugin_remove"), visibility("default")));

#undef xfce_panel_plugin_position_widget 
extern __typeof (xfce_panel_plugin_position_widget) xfce_panel_plugin_position_widget __attribute((alias("IA__xfce_panel_plugin_position_widget"), visibility("default")));

#undef xfce_panel_plugin_position_menu 
extern __typeof (xfce_panel_plugin_position_menu) xfce_panel_plugin_position_menu __attribute((alias("IA__xfce_panel_plugin_position_menu"), visibility("default")));

#undef xfce_panel_plugin_focus_widget 
extern __typeof (xfce_panel_plugin_focus_widget) xfce_panel_plugin_focus_widget __attribute((alias("IA__xfce_panel_plugin_focus_widget"), visibility("default")));

#undef xfce_panel_plugin_block_autohide 
extern __typeof (xfce_panel_plugin_block_autohide) xfce_panel_plugin_block_autohide __attribute((alias("IA__xfce_panel_plugin_block_autohide"), visibility("default")));

#undef xfce_panel_plugin_lookup_rc_file 
extern __typeof (xfce_panel_plugin_lookup_rc_file) xfce_panel_plugin_lookup_rc_file __attribute((alias("IA__xfce_panel_plugin_lookup_rc_file"), visibility("default")));

#undef xfce_panel_plugin_save_location 
extern __typeof (xfce_panel_plugin_save_location) xfce_panel_plugin_save_location __attribute((alias("IA__xfce_panel_plugin_save_location"), visibility("default")));

#endif
#endif
#if IN_HEADER(__XFCE_PANEL_PLUGIN_PROVIDER_H__)
#if IN_SOURCE(__XFCE_PANEL_PLUGIN_PROVIDER_C__)
#undef xfce_panel_plugin_provider_ask_remove 
extern __typeof (xfce_panel_plugin_provider_ask_remove) xfce_panel_plugin_provider_ask_remove __attribute((alias("IA__xfce_panel_plugin_provider_ask_remove"), visibility("default")));

#undef xfce_panel_plugin_provider_get_type 
extern __typeof (xfce_panel_plugin_provider_get_type) xfce_panel_plugin_provider_get_type __attribute((alias("IA__xfce_panel_plugin_provider_get_type"), visibility("default")));

#undef xfce_panel_plugin_provider_get_name 
extern __typeof (xfce_panel_plugin_provider_get_name) xfce_panel_plugin_provider_get_name __attribute((alias("IA__xfce_panel_plugin_provider_get_name"), visibility("default")));

#undef xfce_panel_plugin_provider_get_unique_id 
extern __typeof (xfce_panel_plugin_provider_get_unique_id) xfce_panel_plugin_provider_get_unique_id __attribute((alias("IA__xfce_panel_plugin_provider_get_unique_id"), visibility("default")));

#undef xfce_panel_plugin_provider_set_size 
extern __typeof (xfce_panel_plugin_provider_set_size) xfce_panel_plugin_provider_set_size __attribute((alias("IA__xfce_panel_plugin_provider_set_size"), visibility("default")));

#undef xfce_panel_plugin_provider_set_mode 
extern __typeof (xfce_panel_plugin_provider_set_mode) xfce_panel_plugin_provider_set_mode __attribute((alias("IA__xfce_panel_plugin_provider_set_mode"), visibility("default")));

#undef xfce_panel_plugin_provider_set_nrows 
extern __typeof (xfce_panel_plugin_provider_set_nrows) xfce_panel_plugin_provider_set_nrows __attribute((alias("IA__xfce_panel_plugin_provider_set_nrows"), visibility("default")));

#undef xfce_panel_plugin_provider_set_screen_position 
extern __typeof (xfce_panel_plugin_provider_set_screen_position) xfce_panel_plugin_provider_set_screen_position __attribute((alias("IA__xfce_panel_plugin_provider_set_screen_position"), visibility("default")));

#undef xfce_panel_plugin_provider_save 
extern __typeof (xfce_panel_plugin_provider_save) xfce_panel_plugin_provider_save __attribute((alias("IA__xfce_panel_plugin_provider_save"), visibility("default")));

#undef xfce_panel_plugin_provider_emit_signal 
extern __typeof (xfce_panel_plugin_provider_emit_signal) xfce_panel_plugin_provider_emit_signal __attribute((alias("IA__xfce_panel_plugin_provider_emit_signal"), visibility("default")));

#undef xfce_panel_plugin_provider_get_show_configure 
extern __typeof (xfce_panel_plugin_provider_get_show_configure) xfce_panel_plugin_provider_get_show_configure __attribute((alias("IA__xfce_panel_plugin_provider_get_show_configure"), visibility("default")));

#undef xfce_panel_plugin_provider_show_configure 
extern __typeof (xfce_panel_plugin_provider_show_configure) xfce_panel_plugin_provider_show_configure __attribute((alias("IA__xfce_panel_plugin_provider_show_configure"), visibility("default")));

#undef xfce_panel_plugin_provider_get_show_about 
extern __typeof (xfce_panel_plugin_provider_get_show_about) xfce_panel_plugin_provider_get_show_about __attribute((alias("IA__xfce_panel_plugin_provider_get_show_about"), visibility("default")));

#undef xfce_panel_plugin_provider_show_about 
extern __typeof (xfce_panel_plugin_provider_show_about) xfce_panel_plugin_provider_show_about __attribute((alias("IA__xfce_panel_plugin_provider_show_about"), visibility("default")));

#undef xfce_panel_plugin_provider_removed 
extern __typeof (xfce_panel_plugin_provider_removed) xfce_panel_plugin_provider_removed __attribute((alias("IA__xfce_panel_plugin_provider_removed"), visibility("default")));

#undef xfce_panel_plugin_provider_remote_event 
extern __typeof (xfce_panel_plugin_provider_remote_event) xfce_panel_plugin_provider_remote_event __attribute((alias("IA__xfce_panel_plugin_provider_remote_event"), visibility("default")));

#undef xfce_panel_plugin_provider_set_locked 
extern __typeof (xfce_panel_plugin_provider_set_locked) xfce_panel_plugin_provider_set_locked __attribute((alias("IA__xfce_panel_plugin_provider_set_locked"), visibility("default")));

#endif
#endif

#endif /* HAVE_GNUC_VISIBILITY */
