/* Generated by make-libxfce4panel-alias.pl. Do not edit this file. */

#ifdef HAVE_GNUC_VISIBILITY

#include <glib.h>

#define IN_HEADER defined
#define IN_SOURCE(x) 1

#if IN_HEADER(__LIBXFCE4PANEL_CONFIG_H__)
#if IN_SOURCE(__LIBXFCE4PANEL_CONFIG_C__)
extern __typeof (libxfce4panel_check_version) IA__libxfce4panel_check_version __attribute((visibility("hidden")));
#define libxfce4panel_check_version IA__libxfce4panel_check_version

extern __typeof (libxfce4panel_major_version) IA__libxfce4panel_major_version __attribute((visibility("hidden")));
#define libxfce4panel_major_version IA__libxfce4panel_major_version

extern __typeof (libxfce4panel_micro_version) IA__libxfce4panel_micro_version __attribute((visibility("hidden")));
#define libxfce4panel_micro_version IA__libxfce4panel_micro_version

extern __typeof (libxfce4panel_minor_version) IA__libxfce4panel_minor_version __attribute((visibility("hidden")));
#define libxfce4panel_minor_version IA__libxfce4panel_minor_version

#endif
#endif
#if IN_HEADER(__LIBXFCE4PANEL_ENUM_TYPES_H__)
#if IN_SOURCE(__LIBXFCE4PANEL_ENUM_TYPES_C__)
extern __typeof (xfce_screen_position_get_type) IA__xfce_screen_position_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define xfce_screen_position_get_type IA__xfce_screen_position_get_type

extern __typeof (xfce_panel_plugin_mode_get_type) IA__xfce_panel_plugin_mode_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define xfce_panel_plugin_mode_get_type IA__xfce_panel_plugin_mode_get_type

#endif
#endif
#if IN_HEADER(__XFCE_ARROW_BUTTON_H__)
#if IN_SOURCE(__XFCE_ARROW_BUTTON_C__)
extern __typeof (xfce_arrow_button_get_type) IA__xfce_arrow_button_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define xfce_arrow_button_get_type IA__xfce_arrow_button_get_type

extern __typeof (xfce_arrow_button_new) IA__xfce_arrow_button_new __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define xfce_arrow_button_new IA__xfce_arrow_button_new

extern __typeof (xfce_arrow_button_get_arrow_type) IA__xfce_arrow_button_get_arrow_type __attribute((visibility("hidden")));
#define xfce_arrow_button_get_arrow_type IA__xfce_arrow_button_get_arrow_type

extern __typeof (xfce_arrow_button_set_arrow_type) IA__xfce_arrow_button_set_arrow_type __attribute((visibility("hidden")));
#define xfce_arrow_button_set_arrow_type IA__xfce_arrow_button_set_arrow_type

extern __typeof (xfce_arrow_button_get_blinking) IA__xfce_arrow_button_get_blinking __attribute((visibility("hidden")));
#define xfce_arrow_button_get_blinking IA__xfce_arrow_button_get_blinking

extern __typeof (xfce_arrow_button_set_blinking) IA__xfce_arrow_button_set_blinking __attribute((visibility("hidden")));
#define xfce_arrow_button_set_blinking IA__xfce_arrow_button_set_blinking

#endif
#endif
#if IN_HEADER(__XFCE_HVBOX_H__)
#if IN_SOURCE(__XFCE_HVBOX_C__)
extern __typeof (xfce_hvbox_get_type) IA__xfce_hvbox_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define xfce_hvbox_get_type IA__xfce_hvbox_get_type

extern __typeof (xfce_hvbox_new) IA__xfce_hvbox_new __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define xfce_hvbox_new IA__xfce_hvbox_new

extern __typeof (xfce_hvbox_set_orientation) IA__xfce_hvbox_set_orientation __attribute((visibility("hidden")));
#define xfce_hvbox_set_orientation IA__xfce_hvbox_set_orientation

extern __typeof (xfce_hvbox_get_orientation) IA__xfce_hvbox_get_orientation __attribute((visibility("hidden")));
#define xfce_hvbox_get_orientation IA__xfce_hvbox_get_orientation

#endif
#endif
#if IN_HEADER(__XFCE_PANEL_CONVENIENCE_H__)
#if IN_SOURCE(__XFCE_PANEL_CONVENIENCE_C__)
extern __typeof (xfce_panel_create_button) IA__xfce_panel_create_button __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define xfce_panel_create_button IA__xfce_panel_create_button

extern __typeof (xfce_panel_create_toggle_button) IA__xfce_panel_create_toggle_button __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define xfce_panel_create_toggle_button IA__xfce_panel_create_toggle_button

extern __typeof (xfce_panel_get_channel_name) IA__xfce_panel_get_channel_name __attribute((visibility("hidden")));
#define xfce_panel_get_channel_name IA__xfce_panel_get_channel_name

extern __typeof (xfce_panel_pixbuf_from_source) IA__xfce_panel_pixbuf_from_source __attribute((visibility("hidden")));
#define xfce_panel_pixbuf_from_source IA__xfce_panel_pixbuf_from_source

extern __typeof (xfce_panel_pixbuf_from_source_at_size) IA__xfce_panel_pixbuf_from_source_at_size __attribute((visibility("hidden")));
#define xfce_panel_pixbuf_from_source_at_size IA__xfce_panel_pixbuf_from_source_at_size

#endif
#endif
#if IN_HEADER(__XFCE_PANEL_IMAGE_H__)
#if IN_SOURCE(__XFCE_PANEL_IMAGE_C__)
extern __typeof (xfce_panel_image_get_type) IA__xfce_panel_image_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define xfce_panel_image_get_type IA__xfce_panel_image_get_type

extern __typeof (xfce_panel_image_new) IA__xfce_panel_image_new __attribute((visibility("hidden"))) G_GNUC_MALLOC;
#define xfce_panel_image_new IA__xfce_panel_image_new

extern __typeof (xfce_panel_image_new_from_pixbuf) IA__xfce_panel_image_new_from_pixbuf __attribute((visibility("hidden"))) G_GNUC_MALLOC;
#define xfce_panel_image_new_from_pixbuf IA__xfce_panel_image_new_from_pixbuf

extern __typeof (xfce_panel_image_new_from_source) IA__xfce_panel_image_new_from_source __attribute((visibility("hidden"))) G_GNUC_MALLOC;
#define xfce_panel_image_new_from_source IA__xfce_panel_image_new_from_source

extern __typeof (xfce_panel_image_set_from_pixbuf) IA__xfce_panel_image_set_from_pixbuf __attribute((visibility("hidden")));
#define xfce_panel_image_set_from_pixbuf IA__xfce_panel_image_set_from_pixbuf

extern __typeof (xfce_panel_image_set_from_source) IA__xfce_panel_image_set_from_source __attribute((visibility("hidden")));
#define xfce_panel_image_set_from_source IA__xfce_panel_image_set_from_source

extern __typeof (xfce_panel_image_set_size) IA__xfce_panel_image_set_size __attribute((visibility("hidden")));
#define xfce_panel_image_set_size IA__xfce_panel_image_set_size

extern __typeof (xfce_panel_image_get_size) IA__xfce_panel_image_get_size __attribute((visibility("hidden")));
#define xfce_panel_image_get_size IA__xfce_panel_image_get_size

extern __typeof (xfce_panel_image_clear) IA__xfce_panel_image_clear __attribute((visibility("hidden")));
#define xfce_panel_image_clear IA__xfce_panel_image_clear

#endif
#endif
#if IN_HEADER(__XFCE_PANEL_PLUGIN_H__)
#if IN_SOURCE(__XFCE_PANEL_PLUGIN_C__)
extern __typeof (xfce_panel_plugin_get_type) IA__xfce_panel_plugin_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define xfce_panel_plugin_get_type IA__xfce_panel_plugin_get_type

extern __typeof (xfce_panel_plugin_get_name) IA__xfce_panel_plugin_get_name __attribute((visibility("hidden"))) G_GNUC_PURE;
#define xfce_panel_plugin_get_name IA__xfce_panel_plugin_get_name

extern __typeof (xfce_panel_plugin_get_display_name) IA__xfce_panel_plugin_get_display_name __attribute((visibility("hidden"))) G_GNUC_PURE;
#define xfce_panel_plugin_get_display_name IA__xfce_panel_plugin_get_display_name

extern __typeof (xfce_panel_plugin_get_comment) IA__xfce_panel_plugin_get_comment __attribute((visibility("hidden"))) G_GNUC_PURE;
#define xfce_panel_plugin_get_comment IA__xfce_panel_plugin_get_comment

extern __typeof (xfce_panel_plugin_get_unique_id) IA__xfce_panel_plugin_get_unique_id __attribute((visibility("hidden"))) G_GNUC_PURE;
#define xfce_panel_plugin_get_unique_id IA__xfce_panel_plugin_get_unique_id

extern __typeof (xfce_panel_plugin_get_property_base) IA__xfce_panel_plugin_get_property_base __attribute((visibility("hidden"))) G_GNUC_PURE;
#define xfce_panel_plugin_get_property_base IA__xfce_panel_plugin_get_property_base

extern __typeof (xfce_panel_plugin_get_arguments) IA__xfce_panel_plugin_get_arguments __attribute((visibility("hidden"))) G_GNUC_PURE;
#define xfce_panel_plugin_get_arguments IA__xfce_panel_plugin_get_arguments

extern __typeof (xfce_panel_plugin_get_size) IA__xfce_panel_plugin_get_size __attribute((visibility("hidden"))) G_GNUC_PURE;
#define xfce_panel_plugin_get_size IA__xfce_panel_plugin_get_size

extern __typeof (xfce_panel_plugin_get_small) IA__xfce_panel_plugin_get_small __attribute((visibility("hidden"))) G_GNUC_PURE;
#define xfce_panel_plugin_get_small IA__xfce_panel_plugin_get_small

extern __typeof (xfce_panel_plugin_get_expand) IA__xfce_panel_plugin_get_expand __attribute((visibility("hidden"))) G_GNUC_PURE;
#define xfce_panel_plugin_get_expand IA__xfce_panel_plugin_get_expand

extern __typeof (xfce_panel_plugin_set_expand) IA__xfce_panel_plugin_set_expand __attribute((visibility("hidden")));
#define xfce_panel_plugin_set_expand IA__xfce_panel_plugin_set_expand

extern __typeof (xfce_panel_plugin_get_shrink) IA__xfce_panel_plugin_get_shrink __attribute((visibility("hidden"))) G_GNUC_PURE;
#define xfce_panel_plugin_get_shrink IA__xfce_panel_plugin_get_shrink

extern __typeof (xfce_panel_plugin_set_shrink) IA__xfce_panel_plugin_set_shrink __attribute((visibility("hidden")));
#define xfce_panel_plugin_set_shrink IA__xfce_panel_plugin_set_shrink

extern __typeof (xfce_panel_plugin_set_small) IA__xfce_panel_plugin_set_small __attribute((visibility("hidden")));
#define xfce_panel_plugin_set_small IA__xfce_panel_plugin_set_small

extern __typeof (xfce_panel_plugin_get_locked) IA__xfce_panel_plugin_get_locked __attribute((visibility("hidden")));
#define xfce_panel_plugin_get_locked IA__xfce_panel_plugin_get_locked

extern __typeof (xfce_panel_plugin_get_orientation) IA__xfce_panel_plugin_get_orientation __attribute((visibility("hidden"))) G_GNUC_PURE;
#define xfce_panel_plugin_get_orientation IA__xfce_panel_plugin_get_orientation

extern __typeof (xfce_panel_plugin_get_mode) IA__xfce_panel_plugin_get_mode __attribute((visibility("hidden"))) G_GNUC_PURE;
#define xfce_panel_plugin_get_mode IA__xfce_panel_plugin_get_mode

extern __typeof (xfce_panel_plugin_get_nrows) IA__xfce_panel_plugin_get_nrows __attribute((visibility("hidden"))) G_GNUC_PURE;
#define xfce_panel_plugin_get_nrows IA__xfce_panel_plugin_get_nrows

extern __typeof (xfce_panel_plugin_get_screen_position) IA__xfce_panel_plugin_get_screen_position __attribute((visibility("hidden"))) G_GNUC_PURE;
#define xfce_panel_plugin_get_screen_position IA__xfce_panel_plugin_get_screen_position

extern __typeof (xfce_panel_plugin_take_window) IA__xfce_panel_plugin_take_window __attribute((visibility("hidden")));
#define xfce_panel_plugin_take_window IA__xfce_panel_plugin_take_window

extern __typeof (xfce_panel_plugin_add_action_widget) IA__xfce_panel_plugin_add_action_widget __attribute((visibility("hidden")));
#define xfce_panel_plugin_add_action_widget IA__xfce_panel_plugin_add_action_widget

extern __typeof (xfce_panel_plugin_menu_insert_item) IA__xfce_panel_plugin_menu_insert_item __attribute((visibility("hidden")));
#define xfce_panel_plugin_menu_insert_item IA__xfce_panel_plugin_menu_insert_item

extern __typeof (xfce_panel_plugin_menu_show_configure) IA__xfce_panel_plugin_menu_show_configure __attribute((visibility("hidden")));
#define xfce_panel_plugin_menu_show_configure IA__xfce_panel_plugin_menu_show_configure

extern __typeof (xfce_panel_plugin_menu_show_about) IA__xfce_panel_plugin_menu_show_about __attribute((visibility("hidden")));
#define xfce_panel_plugin_menu_show_about IA__xfce_panel_plugin_menu_show_about

extern __typeof (xfce_panel_plugin_block_menu) IA__xfce_panel_plugin_block_menu __attribute((visibility("hidden")));
#define xfce_panel_plugin_block_menu IA__xfce_panel_plugin_block_menu

extern __typeof (xfce_panel_plugin_unblock_menu) IA__xfce_panel_plugin_unblock_menu __attribute((visibility("hidden")));
#define xfce_panel_plugin_unblock_menu IA__xfce_panel_plugin_unblock_menu

extern __typeof (xfce_panel_plugin_register_menu) IA__xfce_panel_plugin_register_menu __attribute((visibility("hidden")));
#define xfce_panel_plugin_register_menu IA__xfce_panel_plugin_register_menu

extern __typeof (xfce_panel_plugin_arrow_type) IA__xfce_panel_plugin_arrow_type __attribute((visibility("hidden")));
#define xfce_panel_plugin_arrow_type IA__xfce_panel_plugin_arrow_type

extern __typeof (xfce_panel_plugin_remove) IA__xfce_panel_plugin_remove __attribute((visibility("hidden")));
#define xfce_panel_plugin_remove IA__xfce_panel_plugin_remove

extern __typeof (xfce_panel_plugin_position_widget) IA__xfce_panel_plugin_position_widget __attribute((visibility("hidden")));
#define xfce_panel_plugin_position_widget IA__xfce_panel_plugin_position_widget

extern __typeof (xfce_panel_plugin_position_menu) IA__xfce_panel_plugin_position_menu __attribute((visibility("hidden")));
#define xfce_panel_plugin_position_menu IA__xfce_panel_plugin_position_menu

extern __typeof (xfce_panel_plugin_focus_widget) IA__xfce_panel_plugin_focus_widget __attribute((visibility("hidden")));
#define xfce_panel_plugin_focus_widget IA__xfce_panel_plugin_focus_widget

extern __typeof (xfce_panel_plugin_block_autohide) IA__xfce_panel_plugin_block_autohide __attribute((visibility("hidden")));
#define xfce_panel_plugin_block_autohide IA__xfce_panel_plugin_block_autohide

extern __typeof (xfce_panel_plugin_lookup_rc_file) IA__xfce_panel_plugin_lookup_rc_file __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define xfce_panel_plugin_lookup_rc_file IA__xfce_panel_plugin_lookup_rc_file

extern __typeof (xfce_panel_plugin_save_location) IA__xfce_panel_plugin_save_location __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define xfce_panel_plugin_save_location IA__xfce_panel_plugin_save_location

#endif
#endif
#if IN_HEADER(__XFCE_PANEL_PLUGIN_PROVIDER_H__)
#if IN_SOURCE(__XFCE_PANEL_PLUGIN_PROVIDER_C__)
extern __typeof (xfce_panel_plugin_provider_ask_remove) IA__xfce_panel_plugin_provider_ask_remove __attribute((visibility("hidden")));
#define xfce_panel_plugin_provider_ask_remove IA__xfce_panel_plugin_provider_ask_remove

extern __typeof (xfce_panel_plugin_provider_get_type) IA__xfce_panel_plugin_provider_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define xfce_panel_plugin_provider_get_type IA__xfce_panel_plugin_provider_get_type

extern __typeof (xfce_panel_plugin_provider_get_name) IA__xfce_panel_plugin_provider_get_name __attribute((visibility("hidden")));
#define xfce_panel_plugin_provider_get_name IA__xfce_panel_plugin_provider_get_name

extern __typeof (xfce_panel_plugin_provider_get_unique_id) IA__xfce_panel_plugin_provider_get_unique_id __attribute((visibility("hidden")));
#define xfce_panel_plugin_provider_get_unique_id IA__xfce_panel_plugin_provider_get_unique_id

extern __typeof (xfce_panel_plugin_provider_set_size) IA__xfce_panel_plugin_provider_set_size __attribute((visibility("hidden")));
#define xfce_panel_plugin_provider_set_size IA__xfce_panel_plugin_provider_set_size

extern __typeof (xfce_panel_plugin_provider_set_mode) IA__xfce_panel_plugin_provider_set_mode __attribute((visibility("hidden")));
#define xfce_panel_plugin_provider_set_mode IA__xfce_panel_plugin_provider_set_mode

extern __typeof (xfce_panel_plugin_provider_set_nrows) IA__xfce_panel_plugin_provider_set_nrows __attribute((visibility("hidden")));
#define xfce_panel_plugin_provider_set_nrows IA__xfce_panel_plugin_provider_set_nrows

extern __typeof (xfce_panel_plugin_provider_set_screen_position) IA__xfce_panel_plugin_provider_set_screen_position __attribute((visibility("hidden")));
#define xfce_panel_plugin_provider_set_screen_position IA__xfce_panel_plugin_provider_set_screen_position

extern __typeof (xfce_panel_plugin_provider_save) IA__xfce_panel_plugin_provider_save __attribute((visibility("hidden")));
#define xfce_panel_plugin_provider_save IA__xfce_panel_plugin_provider_save

extern __typeof (xfce_panel_plugin_provider_emit_signal) IA__xfce_panel_plugin_provider_emit_signal __attribute((visibility("hidden")));
#define xfce_panel_plugin_provider_emit_signal IA__xfce_panel_plugin_provider_emit_signal

extern __typeof (xfce_panel_plugin_provider_get_show_configure) IA__xfce_panel_plugin_provider_get_show_configure __attribute((visibility("hidden")));
#define xfce_panel_plugin_provider_get_show_configure IA__xfce_panel_plugin_provider_get_show_configure

extern __typeof (xfce_panel_plugin_provider_show_configure) IA__xfce_panel_plugin_provider_show_configure __attribute((visibility("hidden")));
#define xfce_panel_plugin_provider_show_configure IA__xfce_panel_plugin_provider_show_configure

extern __typeof (xfce_panel_plugin_provider_get_show_about) IA__xfce_panel_plugin_provider_get_show_about __attribute((visibility("hidden")));
#define xfce_panel_plugin_provider_get_show_about IA__xfce_panel_plugin_provider_get_show_about

extern __typeof (xfce_panel_plugin_provider_show_about) IA__xfce_panel_plugin_provider_show_about __attribute((visibility("hidden")));
#define xfce_panel_plugin_provider_show_about IA__xfce_panel_plugin_provider_show_about

extern __typeof (xfce_panel_plugin_provider_removed) IA__xfce_panel_plugin_provider_removed __attribute((visibility("hidden")));
#define xfce_panel_plugin_provider_removed IA__xfce_panel_plugin_provider_removed

extern __typeof (xfce_panel_plugin_provider_remote_event) IA__xfce_panel_plugin_provider_remote_event __attribute((visibility("hidden")));
#define xfce_panel_plugin_provider_remote_event IA__xfce_panel_plugin_provider_remote_event

extern __typeof (xfce_panel_plugin_provider_set_locked) IA__xfce_panel_plugin_provider_set_locked __attribute((visibility("hidden")));
#define xfce_panel_plugin_provider_set_locked IA__xfce_panel_plugin_provider_set_locked

#endif
#endif

#endif /* HAVE_GNUC_VISIBILITY */
