/* automatically generated from actions-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (actions_dialog_ui)
#endif
#ifdef __GNUC__
static const char actions_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char actions_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"2.24\"/><object class=\"XfceTitledDialog\" id=\"dialog\""
  "><property name=\"can_focus\">False</property><property name=\"title\" "
  "translatable=\"yes\">Action Buttons</property><property name=\"default_"
  "width\">300</property><property name=\"default_height\">450</property><"
  "property name=\"icon_name\">gtk-properties</property><property name=\"t"
  "ype_hint\">normal</property><child internal-child=\"vbox\"><object clas"
  "s=\"GtkVBox\" id=\"dialog-vbox1\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property><property name=\"spac"
  "ing\">2</property><child internal-child=\"action_area\"><object class=\""
  "GtkHButtonBox\" id=\"dialog-action_area1\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"layout_style\">end</property><child><object class=\"GtkButton\" id"
  "=\"close-button\"><property name=\"label\">gtk-close</property><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">True</pr"
  "operty><property name=\"receives_default\">True</property><property nam"
  "e=\"use_action_appearance\">False</property><property name=\"use_stock\""
  ">True</property></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"fill\">False</property><property name=\"position\""
  ">0</property></packing></child><child><object class=\"GtkButton\" id=\""
  "help-button\"><property name=\"label\">gtk-help</property><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">True</propert"
  "y><property name=\"receives_default\">True</property><property name=\"u"
  "se_action_appearance\">False</property><property name=\"use_stock\">Tru"
  "e</property></object><packing><property name=\"expand\">False</property"
  "><property name=\"fill\">False</property><property name=\"position\">1<"
  "/property><property name=\"secondary\">True</property></packing></child"
  "></object><packing><property name=\"expand\">False</property><property "
  "name=\"fill\">True</property><property name=\"pack_type\">end</property"
  "><property name=\"position\">0</property></packing></child><child><obje"
  "ct class=\"GtkVBox\" id=\"vbox1\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property><property name=\"bord"
  "er_width\">6</property><property name=\"spacing\">6</property><child><o"
  "bject class=\"GtkFrame\" id=\"frame1\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "label_xalign\">0</property><property name=\"shadow_type\">none</propert"
  "y><child><object class=\"GtkAlignment\" id=\"alignment1\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty><property name=\"left_padding\">12</property><child><object class=\""
  "GtkTable\" id=\"table1\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"border_width\""
  ">6</property><property name=\"n_rows\">3</property><property name=\"n_c"
  "olumns\">2</property><property name=\"column_spacing\">12</property><pr"
  "operty name=\"row_spacing\">6</property><child><object class=\"GtkLabel"
  "\" id=\"label3\"><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">False</property><property name=\"xalign\">0</property>"
  "<property name=\"label\" translatable=\"yes\">Appeara_nce:</property><p"
  "roperty name=\"use_underline\">True</property><property name=\"mnemonic"
  "_widget\">combo-mode</property></object><packing><property name=\"x_opt"
  "ions\">GTK_FILL</property></packing></child><child><object class=\"GtkC"
  "heckButton\" id=\"invert-orientation\"><property name=\"label\" transla"
  "table=\"yes\">Invert buttons _orientation</property><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">True</property><pro"
  "perty name=\"receives_default\">False</property><property name=\"use_ac"
  "tion_appearance\">False</property><property name=\"use_underline\">True"
  "</property><property name=\"draw_indicator\">True</property></object><p"
  "acking><property name=\"right_attach\">2</property><property name=\"top"
  "_attach\">1</property><property name=\"bottom_attach\">2</property></pa"
  "cking></child><child><object class=\"GtkComboBox\" id=\"combo-mode\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><property name=\"model\">mode-store</property><child><obj"
  "ect class=\"GtkCellRendererText\" id=\"cellrenderertext2\"/><attributes"
  "><attribute name=\"text\">0</attribute></attributes></child></object><p"
  "acking><property name=\"left_attach\">1</property><property name=\"righ"
  "t_attach\">2</property></packing></child><child><object class=\"GtkChec"
  "kButton\" id=\"confirmation-dialog\"><property name=\"label\" translata"
  "ble=\"yes\">_Show confirmation dialog</property><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">True</property><propert"
  "y name=\"receives_default\">False</property><property name=\"tooltip_te"
  "xt\" translatable=\"yes\">Show a confirmation dialog with a 30 second t"
  "imeout for some of the actions.</property><property name=\"use_action_a"
  "ppearance\">False</property><property name=\"use_underline\">True</prop"
  "erty><property name=\"draw_indicator\">True</property></object><packing"
  "><property name=\"right_attach\">2</property><property name=\"top_attac"
  "h\">2</property><property name=\"bottom_attach\">3</property></packing>"
  "</child></object></child></object></child><child type=\"label\"><object"
  " class=\"GtkLabel\" id=\"label1\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property><property name=\"labe"
  "l\" translatable=\"yes\">General</property><attributes><attribute name="
  "\"weight\" value=\"bold\"/></attributes></object></child></object><pack"
  "ing><property name=\"expand\">False</property><property name=\"fill\">T"
  "rue</property><property name=\"position\">0</property></packing></child"
  "><child><object class=\"GtkFrame\" id=\"frame2\"><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">False</property><prope"
  "rty name=\"label_xalign\">0</property><property name=\"shadow_type\">no"
  "ne</property><child><object class=\"GtkAlignment\" id=\"alignment2\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><property name=\"left_padding\">12</property><child><obje"
  "ct class=\"GtkScrolledWindow\" id=\"scrolledwindow1\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"border_width\">6</property><property name=\"hscrollbar_p"
  "olicy\">automatic</property><property name=\"vscrollbar_policy\">automa"
  "tic</property><property name=\"shadow_type\">etched-in</property><child"
  "><object class=\"GtkTreeView\" id=\"actions-treeview\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"model\">items-store</property><property name=\"headers_c"
  "lickable\">False</property><property name=\"reorderable\">True</propert"
  "y><property name=\"search_column\">0</property><child><object class=\"G"
  "tkTreeViewColumn\" id=\"treeviewcolumn1\"><property name=\"title\" tran"
  "slatable=\"yes\">Visible</property><child><object class=\"GtkCellRender"
  "erToggle\" id=\"visible-toggle\"/><attributes><attribute name=\"active\""
  ">0</attribute></attributes></child></object></child><child><object clas"
  "s=\"GtkTreeViewColumn\" id=\"treeviewcolumn2\"><property name=\"title\""
  " translatable=\"yes\">Action</property><child><object class=\"GtkCellRe"
  "ndererText\" id=\"text-renderer\"/><attributes><attribute name=\"markup"
  "\">1</attribute></attributes></child></object></child></object></child>"
  "</object></child></object></child><child type=\"label\"><object class=\""
  "GtkLabel\" id=\"label2\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"label\" trans"
  "latable=\"yes\">_Actions</property><property name=\"use_underline\">Tru"
  "e</property><property name=\"mnemonic_widget\">actions-treeview</proper"
  "ty><attributes><attribute name=\"weight\" value=\"bold\"/></attributes>"
  "</object></child></object><packing><property name=\"expand\">True</prop"
  "erty><property name=\"fill\">True</property><property name=\"position\""
  ">1</property></packing></child></object><packing><property name=\"expan"
  "d\">True</property><property name=\"fill\">True</property><property nam"
  "e=\"position\">1</property></packing></child></object></child><action-w"
  "idgets><action-widget response=\"0\">close-button</action-widget><actio"
  "n-widget response=\"0\">help-button</action-widget></action-widgets></o"
  "bject><object class=\"GtkListStore\" id=\"items-store\"><columns><colum"
  "n type=\"gboolean\"/><column type=\"gchararray\"/><column type=\"gchara"
  "rray\"/><column type=\"guint\"/></columns></object><object class=\"GtkL"
  "istStore\" id=\"mode-store\"><columns><column type=\"gchararray\"/></co"
  "lumns><data><row><col id=\"0\" translatable=\"yes\">Action Buttons</col"
  "></row><row><col id=\"0\" translatable=\"yes\">Session Menu</col></row>"
  "</data></object></interface>"
};

static const unsigned actions_dialog_ui_length = 8489u;

