.TH XFCE4-PANEL "1" "August 2013" "xfce4-panel" "User Commands"
.SH NAME
xfce4-panel \- A panel for the Xfce4 desktop environment
.SH DESCRIPTION
.SS "Usage:"
.IP
xfce4\-panel [OPTION...] [ARGUMENTS...]
.SS "Help Options:"
.TP
\fB\-h\fR, \fB\-\-help\fR
Show help options
.TP
\fB\-\-help\-all\fR
Show all help options
.TP
\fB\-\-help\-gtk\fR
Show GTK+ Options
.TP
\fB\-\-help\-sm\-client\fR
Show session management options
.PP
GTK+ Options
.TP
\fB\-\-class\fR=\fICLASS\fR
Program class as used by the window manager
.TP
\fB\-\-name\fR=\fINAME\fR
Program name as used by the window manager
.TP
\fB\-\-screen\fR=\fISCREEN\fR
X screen to use
.TP
\fB\-\-sync\fR
Make X calls synchronous
.TP
\fB\-\-gtk\-module\fR=\fIMODULES\fR
Load additional GTK+ modules
.TP
\fB\-\-g\-fatal\-warnings\fR
Make all warnings fatal
.PP
Session management options
.TP
\fB\-\-sm\-client\-id\fR=\fIID\fR
Session management client ID
.TP
\fB\-\-sm\-client\-disable\fR
Disable session management
.SS "Application Options:"
.TP
\fB\-p\fR, \fB\-\-preferences\fR=\fIPANEL\-NUMBER\fR
Show the 'Panel Preferences' dialog
.TP
\fB\-a\fR, \fB\-\-add\-items\fR=\fIPANEL\-NUMBER\fR
Show the 'Add New Items' dialog
.TP
\fB\-s\fR, \fB\-\-save\fR
Save the panel configuration
.TP
\fB\-\-add\fR=\fIPLUGIN\-NAME\fR
Add a new plugin to the panel
.TP
\fB\-r\fR, \fB\-\-restart\fR
Restart the running panel instance
.TP
\fB\-q\fR, \fB\-\-quit\fR
Quit the running panel instance
.TP
\fB\-d\fR, \fB\-\-disable\-wm\-check\fR
Do not wait for a window manager on startup
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version information and exit
.TP
\fB\-\-display\fR=\fIDISPLAY\fR
X display to use
.SH "REPORTING BUGS"
Report bugs to http://bugs.debian.org
.SH COPYRIGHT
Copyright \(co 2004\-2011
.IP
The Xfce development team. All rights reserved.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH SEE ALSO
Upstream documentation in /usr/share/doc/xfce4-panel/html/C/index.html


