/* automatically generated from tasklist-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (tasklist_dialog_ui)
#endif
#ifdef __GNUC__
static const char tasklist_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char tasklist_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"2.24\"/><object class=\"GtkListStore\" id=\"grouping-mod"
  "el\"><columns><column type=\"gchararray\"/></columns><data><row><col id"
  "=\"0\" translatable=\"yes\">Never</col></row><row><col id=\"0\" transla"
  "table=\"yes\">Always</col></row><row><col id=\"0\" translatable=\"yes\""
  ">When space is limited</col></row></data></object><object class=\"GtkLi"
  "stStore\" id=\"sort-order-model\"><columns><column type=\"gchararray\"/"
  "></columns><data><row><col id=\"0\" translatable=\"yes\">Timestamp</col"
  "></row><row><col id=\"0\" translatable=\"yes\">Group title and timestam"
  "p</col></row><row><col id=\"0\" translatable=\"yes\">Window title</col>"
  "</row><row><col id=\"0\" translatable=\"yes\">Group title and window ti"
  "tle</col></row><row><col id=\"0\" translatable=\"yes\">None, allow drag"
  "-and-drop</col></row></data></object><object class=\"XfceTitledDialog\""
  " id=\"dialog\"><property name=\"can_focus\">False</property><property n"
  "ame=\"title\" translatable=\"yes\">Window Buttons</property><property n"
  "ame=\"icon_name\">gtk-properties</property><property name=\"type_hint\""
  ">normal</property><child internal-child=\"vbox\"><object class=\"GtkVBo"
  "x\" id=\"dialog-vbox2\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">False</property><property name=\"spacing\">2</p"
  "roperty><child internal-child=\"action_area\"><object class=\"GtkHButto"
  "nBox\" id=\"dialog-action_area2\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property><property name=\"layo"
  "ut_style\">end</property><child><object class=\"GtkButton\" id=\"close-"
  "button\"><property name=\"label\">gtk-close</property><property name=\""
  "use_action_appearance\">False</property><property name=\"visible\">True"
  "</property><property name=\"can_focus\">True</property><property name=\""
  "receives_default\">True</property><property name=\"use_stock\">True</pr"
  "operty></object><packing><property name=\"expand\">False</property><pro"
  "perty name=\"fill\">False</property><property name=\"position\">0</prop"
  "erty></packing></child><child><object class=\"GtkButton\" id=\"help-but"
  "ton\"><property name=\"label\">gtk-help</property><property name=\"use_"
  "action_appearance\">False</property><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">True</property><property name=\"rec"
  "eives_default\">True</property><property name=\"use_stock\">True</prope"
  "rty></object><packing><property name=\"expand\">False</property><proper"
  "ty name=\"fill\">False</property><property name=\"position\">1</propert"
  "y><property name=\"secondary\">True</property></packing></child></objec"
  "t><packing><property name=\"expand\">False</property><property name=\"f"
  "ill\">True</property><property name=\"pack_type\">end</property><proper"
  "ty name=\"position\">0</property></packing></child><child><object class"
  "=\"GtkVBox\" id=\"vbox1\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"border_width"
  "\">6</property><property name=\"spacing\">6</property><child><object cl"
  "ass=\"GtkFrame\" id=\"frame3\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"label_x"
  "align\">0</property><property name=\"shadow_type\">none</property><chil"
  "d><object class=\"GtkAlignment\" id=\"alignment3\"><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">False</property><pro"
  "perty name=\"left_padding\">12</property><child><object class=\"GtkVBox"
  "\" id=\"vbox3\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"border_width\">6</prop"
  "erty><property name=\"spacing\">6</property><child><object class=\"GtkC"
  "heckButton\" id=\"show-labels\"><property name=\"label\" translatable=\""
  "yes\">Show button _labels</property><property name=\"use_action_appeara"
  "nce\">False</property><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">True</property><property name=\"receives_default\""
  ">False</property><property name=\"use_underline\">True</property><prope"
  "rty name=\"draw_indicator\">True</property></object><packing><property "
  "name=\"expand\">True</property><property name=\"fill\">True</property><"
  "property name=\"position\">0</property></packing></child><child><object"
  " class=\"GtkCheckButton\" id=\"flat-buttons\"><property name=\"label\" "
  "translatable=\"yes\">Show _flat buttons</property><property name=\"use_"
  "action_appearance\">False</property><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">True</property><property name=\"rec"
  "eives_default\">False</property><property name=\"use_underline\">True</"
  "property><property name=\"draw_indicator\">True</property></object><pac"
  "king><property name=\"expand\">True</property><property name=\"fill\">T"
  "rue</property><property name=\"position\">1</property></packing></child"
  "><child><object class=\"GtkCheckButton\" id=\"show-handle\"><property n"
  "ame=\"label\" translatable=\"yes\">Show _handle</property><property nam"
  "e=\"use_action_appearance\">False</property><property name=\"visible\">"
  "True</property><property name=\"can_focus\">True</property><property na"
  "me=\"receives_default\">False</property><property name=\"use_underline\""
  ">True</property><property name=\"draw_indicator\">True</property></obje"
  "ct><packing><property name=\"expand\">True</property><property name=\"f"
  "ill\">True</property><property name=\"position\">2</property></packing>"
  "</child><child><object class=\"GtkHBox\" id=\"hbox2\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"spacing\">12</property><child><object class=\"GtkLabel\""
  " id=\"label5\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"label\" translatable=\""
  "yes\">Sorting _order:</property><property name=\"use_underline\">True</"
  "property><property name=\"mnemonic_widget\">sort-order</property></obje"
  "ct><packing><property name=\"expand\">False</property><property name=\""
  "fill\">True</property><property name=\"position\">0</property></packing"
  "></child><child><object class=\"GtkComboBox\" id=\"sort-order\"><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">False</"
  "property><property name=\"model\">sort-order-model</property><child><ob"
  "ject class=\"GtkCellRendererText\" id=\"cellrenderertext1\"/><attribute"
  "s><attribute name=\"text\">0</attribute></attributes></child></object><"
  "packing><property name=\"expand\">False</property><property name=\"fill"
  "\">True</property><property name=\"position\">1</property></packing></c"
  "hild></object><packing><property name=\"expand\">True</property><proper"
  "ty name=\"fill\">True</property><property name=\"position\">3</property"
  "></packing></child></object></child></object></child><child type=\"labe"
  "l\"><object class=\"GtkLabel\" id=\"label1\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"label\" translatable=\"yes\">Appearance</property><attributes><a"
  "ttribute name=\"weight\" value=\"bold\"/></attributes></object></child>"
  "</object><packing><property name=\"expand\">False</property><property n"
  "ame=\"fill\">True</property><property name=\"position\">0</property></p"
  "acking></child><child><object class=\"GtkFrame\" id=\"frame1\"><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">False</p"
  "roperty><property name=\"label_xalign\">0</property><property name=\"sh"
  "adow_type\">none</property><child><object class=\"GtkAlignment\" id=\"a"
  "lignment1\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"left_padding\">12</propert"
  "y><child><object class=\"GtkVBox\" id=\"vbox2\"><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">False</property><proper"
  "ty name=\"border_width\">6</property><property name=\"spacing\">6</prop"
  "erty><child><object class=\"GtkHBox\" id=\"hbox1\"><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">False</property><pro"
  "perty name=\"spacing\">12</property><child><object class=\"GtkLabel\" i"
  "d=\"label4\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"xalign\">0</property><prop"
  "erty name=\"label\" translatable=\"yes\">Window _grouping:</property><p"
  "roperty name=\"use_underline\">True</property><property name=\"mnemonic"
  "_widget\">grouping</property></object><packing><property name=\"expand\""
  ">False</property><property name=\"fill\">True</property><property name="
  "\"position\">0</property></packing></child><child><object class=\"GtkCo"
  "mboBox\" id=\"grouping\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"model\">group"
  "ing-model</property><child><object class=\"GtkCellRendererText\" id=\"c"
  "ellrenderertext2\"/><attributes><attribute name=\"text\">0</attribute><"
  "/attributes></child></object><packing><property name=\"expand\">False</"
  "property><property name=\"fill\">True</property><property name=\"positi"
  "on\">1</property></packing></child></object><packing><property name=\"e"
  "xpand\">True</property><property name=\"fill\">True</property><property"
  " name=\"position\">0</property></packing></child><child><object class=\""
  "GtkHBox\" id=\"hbox3\"><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">False</property><property name=\"spacing\">12</p"
  "roperty><child><object class=\"GtkLabel\" id=\"label6\"><property name="
  "\"visible\">True</property><property name=\"can_focus\">False</property"
  "><property name=\"xalign\">0</property><property name=\"label\" transla"
  "table=\"yes\">Mi_ddle click action:</property><property name=\"use_unde"
  "rline\">True</property><property name=\"mnemonic_widget\">middle-click<"
  "/property></object><packing><property name=\"expand\">False</property><"
  "property name=\"fill\">True</property><property name=\"position\">0</pr"
  "operty></packing></child><child><object class=\"GtkComboBox\" id=\"midd"
  "le-click\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"model\">middle-click-model<"
  "/property><child><object class=\"GtkCellRendererText\" id=\"cellrendere"
  "rtext3\"/><attributes><attribute name=\"text\">0</attribute></attribute"
  "s></child></object><packing><property name=\"expand\">False</property><"
  "property name=\"fill\">True</property><property name=\"position\">1</pr"
  "operty></packing></child></object><packing><property name=\"expand\">Tr"
  "ue</property><property name=\"fill\">True</property><property name=\"po"
  "sition\">1</property></packing></child><child><object class=\"GtkCheckB"
  "utton\" id=\"switch-workspace-on-unminimize\"><property name=\"label\" "
  "translatable=\"yes\">Restore minimized windows to current _workspace</p"
  "roperty><property name=\"use_action_appearance\">False</property><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">True</"
  "property><property name=\"receives_default\">False</property><property "
  "name=\"use_underline\">True</property><property name=\"draw_indicator\""
  ">True</property></object><packing><property name=\"expand\">True</prope"
  "rty><property name=\"fill\">True</property><property name=\"position\">"
  "2</property></packing></child><child><object class=\"GtkCheckButton\" i"
  "d=\"show-wireframes\"><property name=\"label\" translatable=\"yes\">D_r"
  "aw window frame when hovering a button</property><property name=\"use_a"
  "ction_appearance\">False</property><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">True</property><property name=\"rece"
  "ives_default\">False</property><property name=\"use_underline\">True</p"
  "roperty><property name=\"draw_indicator\">True</property></object><pack"
  "ing><property name=\"expand\">True</property><property name=\"fill\">Tr"
  "ue</property><property name=\"position\">3</property></packing></child>"
  "<child><object class=\"GtkCheckButton\" id=\"window-scrolling\"><proper"
  "ty name=\"label\" translatable=\"yes\">_Switch windows using the mouse "
  "wheel</property><property name=\"use_action_appearance\">False</propert"
  "y><property name=\"visible\">True</property><property name=\"can_focus\""
  ">True</property><property name=\"receives_default\">False</property><pr"
  "operty name=\"use_underline\">True</property><property name=\"draw_indi"
  "cator\">True</property></object><packing><property name=\"expand\">True"
  "</property><property name=\"fill\">True</property><property name=\"posi"
  "tion\">4</property></packing></child></object></child></object></child>"
  "<child type=\"label\"><object class=\"GtkLabel\" id=\"label3\"><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">False</p"
  "roperty><property name=\"label\" translatable=\"yes\">Behaviour</proper"
  "ty><attributes><attribute name=\"weight\" value=\"bold\"/></attributes>"
  "</object></child></object><packing><property name=\"expand\">False</pro"
  "perty><property name=\"fill\">True</property><property name=\"position\""
  ">1</property></packing></child><child><object class=\"GtkFrame\" id=\"f"
  "rame2\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"label_xalign\">0</property><pr"
  "operty name=\"shadow_type\">none</property><child><object class=\"GtkAl"
  "ignment\" id=\"alignment2\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">False</property><property name=\"left_paddi"
  "ng\">12</property><child><object class=\"GtkVBox\" id=\"vbox4\"><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">False</"
  "property><property name=\"border_width\">6</property><property name=\"s"
  "pacing\">6</property><child><object class=\"GtkCheckButton\" id=\"inclu"
  "de-all-workspaces\"><property name=\"label\" translatable=\"yes\">Show "
  "windows from _all workspaces or viewports</property><property name=\"us"
  "e_action_appearance\">False</property><property name=\"visible\">True</"
  "property><property name=\"can_focus\">True</property><property name=\"r"
  "eceives_default\">False</property><property name=\"use_underline\">True"
  "</property><property name=\"draw_indicator\">True</property></object><p"
  "acking><property name=\"expand\">True</property><property name=\"fill\""
  ">True</property><property name=\"position\">0</property></packing></chi"
  "ld><child><object class=\"GtkCheckButton\" id=\"include-all-monitors\">"
  "<property name=\"label\" translatable=\"yes\">Show windows from all mo_"
  "nitors</property><property name=\"use_action_appearance\">False</proper"
  "ty><property name=\"visible\">True</property><property name=\"can_focus"
  "\">True</property><property name=\"receives_default\">False</property><"
  "property name=\"use_underline\">True</property><property name=\"draw_in"
  "dicator\">True</property></object><packing><property name=\"expand\">Tr"
  "ue</property><property name=\"fill\">True</property><property name=\"po"
  "sition\">1</property></packing></child><child><object class=\"GtkCheckB"
  "utton\" id=\"show-only-minimized\"><property name=\"label\" translatabl"
  "e=\"yes\">Show only _minimized windows</property><property name=\"use_a"
  "ction_appearance\">False</property><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">True</property><property name=\"rece"
  "ives_default\">False</property><property name=\"use_underline\">True</p"
  "roperty><property name=\"draw_indicator\">True</property></object><pack"
  "ing><property name=\"expand\">True</property><property name=\"fill\">Tr"
  "ue</property><property name=\"position\">1</property></packing></child>"
  "</object></child></object></child><child type=\"label\"><object class=\""
  "GtkLabel\" id=\"label2\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"label\" trans"
  "latable=\"yes\">Filtering</property><attributes><attribute name=\"weigh"
  "t\" value=\"bold\"/></attributes></object></child></object><packing><pr"
  "operty name=\"expand\">True</property><property name=\"fill\">True</pro"
  "perty><property name=\"position\">2</property></packing></child></objec"
  "t><packing><property name=\"expand\">False</property><property name=\"f"
  "ill\">True</property><property name=\"position\">1</property></packing>"
  "</child></object></child><action-widgets><action-widget response=\"0\">"
  "close-button</action-widget><action-widget response=\"0\">help-button</"
  "action-widget></action-widgets></object><object class=\"GtkListStore\" "
  "id=\"middle-click-model\"><columns><column type=\"gchararray\"/></colum"
  "ns><data><row><col id=\"0\" translatable=\"yes\">Nothing</col></row><ro"
  "w><col id=\"0\" translatable=\"yes\">Close Window</col></row><row><col "
  "id=\"0\" translatable=\"yes\">Minimize Window</col></row></data></objec"
  "t><object class=\"GtkSizeGroup\" id=\"sizegroup1\"><widgets><widget nam"
  "e=\"label4\"/><widget name=\"label6\"/></widgets></object></interface>"
};

static const unsigned tasklist_dialog_ui_length = 15769u;

