/* automatically generated from panel-preferences-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (panel_preferences_dialog_ui)
#endif
#ifdef __GNUC__
static const char panel_preferences_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char panel_preferences_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\"?><interface><requires lib=\"gtk+\" version=\"2.24"
  "\"/><object class=\"GtkListStore\" id=\"mode-store\"><columns><column t"
  "ype=\"gchararray\"/></columns><data><row><col id=\"0\" translatable=\"y"
  "es\">Horizontal</col></row><row><col id=\"0\" translatable=\"yes\">Vert"
  "ical</col></row><row><col id=\"0\" translatable=\"yes\">Deskbar</col></"
  "row></data></object><object class=\"GtkListStore\" id=\"panel-store\"><"
  "columns><column type=\"gint\"/><column type=\"gchararray\"/></columns><"
  "/object><object class=\"GtkListStore\" id=\"output-store\"><columns><co"
  "lumn type=\"gchararray\"/><column type=\"gchararray\"/></columns></obje"
  "ct><object class=\"GtkListStore\" id=\"autohide-behavior-store\"><colum"
  "ns><column type=\"gchararray\"/></columns><data><row><col id=\"0\" tran"
  "slatable=\"yes\">Never</col></row><row><col id=\"0\" translatable=\"yes"
  "\">Intelligently</col></row><row><col id=\"0\" translatable=\"yes\">Alw"
  "ays</col></row></data></object><object class=\"GtkListStore\" id=\"styl"
  "es-store\"><columns><column type=\"gchararray\"/></columns><data><row><"
  "col id=\"0\" translatable=\"yes\">None (use system style)</col></row><r"
  "ow><col id=\"0\" translatable=\"yes\">Solid color</col></row><row><col "
  "id=\"0\" translatable=\"yes\">Background image</col></row></data></obje"
  "ct><object class=\"GtkAdjustment\" id=\"size\"><property name=\"value\""
  ">16</property><property name=\"lower\">16</property><property name=\"up"
  "per\">128</property><property name=\"step_increment\">1</property><prop"
  "erty name=\"page_increment\">10</property></object><object class=\"GtkA"
  "djustment\" id=\"length\"><property name=\"value\">25</property><proper"
  "ty name=\"lower\">1</property><property name=\"upper\">100</property><p"
  "roperty name=\"step_increment\">1</property><property name=\"page_incre"
  "ment\">10</property></object><object class=\"GtkAdjustment\" id=\"nrows"
  "\"><property name=\"value\">1</property><property name=\"lower\">1</pro"
  "perty><property name=\"upper\">6</property><property name=\"step_increm"
  "ent\">1</property><property name=\"page_increment\">1</property></objec"
  "t><object class=\"GtkAdjustment\" id=\"background-alpha\"><property nam"
  "e=\"value\">100</property><property name=\"upper\">100</property><prope"
  "rty name=\"step_increment\">1</property><property name=\"page_increment"
  "\">10</property></object><object class=\"GtkAdjustment\" id=\"enter-opa"
  "city\"><property name=\"value\">100</property><property name=\"upper\">"
  "100</property><property name=\"step_increment\">1</property><property n"
  "ame=\"page_increment\">10</property></object><object class=\"GtkAdjustm"
  "ent\" id=\"leave-opacity\"><property name=\"value\">100</property><prop"
  "erty name=\"upper\">100</property><property name=\"step_increment\">1</"
  "property><property name=\"page_increment\">10</property></object><objec"
  "t class=\"GtkImage\" id=\"image10\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"ic"
  "on_name\">package-x-generic</property></object><object class=\"GtkSizeG"
  "roup\" id=\"display-sizegroup\"><widgets><widget name=\"label13\"/><wid"
  "get name=\"label1\"/></widgets></object><object class=\"GtkSizeGroup\" "
  "id=\"bg-sizegroup\"><widgets><widget name=\"label7\"/><widget name=\"la"
  "bel15\"/><widget name=\"label16\"/><widget name=\"label19\"/></widgets>"
  "</object><object class=\"XfceTitledDialog\" id=\"dialog\"><property nam"
  "e=\"title\" translatable=\"yes\">Panel</property><property name=\"windo"
  "w_position\">center-on-parent</property><property name=\"icon_name\">xf"
  "ce4-panel</property><property name=\"type_hint\">normal</property><prop"
  "erty name=\"has_separator\">False</property><child internal-child=\"vbo"
  "x\"><object class=\"GtkVBox\" id=\"dialog-vbox1\"><property name=\"visi"
  "ble\">True</property><property name=\"orientation\">vertical</property>"
  "<property name=\"spacing\">2</property><child><object class=\"GtkVBox\""
  " id=\"plug-child\"><property name=\"visible\">True</property><property "
  "name=\"border_width\">6</property><property name=\"orientation\">vertic"
  "al</property><property name=\"spacing\">12</property><child><object cla"
  "ss=\"GtkHBox\" id=\"hbox3\"><property name=\"visible\">True</property><"
  "property name=\"spacing\">6</property><child><object class=\"GtkComboBo"
  "x\" id=\"panel-combobox\"><property name=\"visible\">True</property><pr"
  "operty name=\"model\">panel-store</property><child><object class=\"GtkC"
  "ellRendererText\" id=\"cellrenderertext2\"/><attributes><attribute name"
  "=\"text\">1</attribute></attributes></child></object><packing><property"
  " name=\"position\">0</property></packing></child><child><object class=\""
  "GtkButton\" id=\"panel-add\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">True</property><property name=\"receives_d"
  "efault\">True</property><property name=\"tooltip_text\" translatable=\""
  "yes\">Add a new panel</property><child><object class=\"GtkImage\" id=\""
  "image1\"><property name=\"visible\">True</property><property name=\"sto"
  "ck\">gtk-add</property></object></child></object><packing><property nam"
  "e=\"expand\">False</property><property name=\"position\">1</property></"
  "packing></child><child><object class=\"GtkButton\" id=\"panel-remove\">"
  "<property name=\"visible\">True</property><property name=\"sensitive\">"
  "False</property><property name=\"can_focus\">True</property><property n"
  "ame=\"receives_default\">True</property><property name=\"tooltip_text\""
  " translatable=\"yes\">Remove the currently selected panel</property><ch"
  "ild><object class=\"GtkImage\" id=\"image2\"><property name=\"visible\""
  ">True</property><property name=\"stock\">gtk-remove</property></object>"
  "</child></object><packing><property name=\"expand\">False</property><pr"
  "operty name=\"position\">2</property></packing></child></object><packin"
  "g><property name=\"expand\">False</property><property name=\"position\""
  ">0</property></packing></child><child><object class=\"GtkHBox\" id=\"hb"
  "ox7\"><property name=\"visible\">True</property><property name=\"spacin"
  "g\">6</property><child><object class=\"GtkButton\" id=\"panel-switch\">"
  "<property name=\"label\">Backup and restore</property><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"receives_default\">True</property><property name=\"toolt"
  "ip_text\" translatable=\"yes\">Switch between panel presets</property><"
  "property name=\"image\">image10</property></object><packing><property n"
  "ame=\"expand\">False</property><property name=\"fill\">True</property><"
  "property name=\"pack_type\">end</property><property name=\"position\">0"
  "</property></packing></child></object><packing><property name=\"expand\""
  ">False</property><property name=\"position\">1</property></packing></ch"
  "ild><child><object class=\"GtkNotebook\" id=\"notebook\"><property name"
  "=\"visible\">True</property><property name=\"sensitive\">False</propert"
  "y><property name=\"can_focus\">True</property><child><object class=\"Gt"
  "kVBox\" id=\"vbox2\"><property name=\"visible\">True</property><propert"
  "y name=\"border_width\">6</property><property name=\"orientation\">vert"
  "ical</property><property name=\"spacing\">6</property><child><object cl"
  "ass=\"GtkFrame\" id=\"frame1\"><property name=\"visible\">True</propert"
  "y><property name=\"label_xalign\">0</property><property name=\"shadow_t"
  "ype\">none</property><child><object class=\"GtkAlignment\" id=\"alignme"
  "nt1\"><property name=\"visible\">True</property><property name=\"left_p"
  "adding\">12</property><child><object class=\"GtkVBox\" id=\"vbox3\"><pr"
  "operty name=\"visible\">True</property><property name=\"border_width\">"
  "6</property><property name=\"orientation\">vertical</property><property"
  " name=\"spacing\">6</property><child><object class=\"GtkHBox\" id=\"hbo"
  "x1\"><property name=\"visible\">True</property><property name=\"spacing"
  "\">12</property><child><object class=\"GtkLabel\" id=\"label1\"><proper"
  "ty name=\"visible\">True</property><property name=\"xalign\">0</propert"
  "y><property name=\"label\" translatable=\"yes\">M_ode:</property><prope"
  "rty name=\"use_underline\">True</property><property name=\"mnemonic_wid"
  "get\">mode</property></object><packing><property name=\"expand\">False<"
  "/property><property name=\"position\">0</property></packing></child><ch"
  "ild><object class=\"GtkComboBox\" id=\"mode\"><property name=\"visible\""
  ">True</property><property name=\"model\">mode-store</property><child><o"
  "bject class=\"GtkCellRendererText\" id=\"cellrenderertext1\"/><attribut"
  "es><attribute name=\"text\">0</attribute></attributes></child></object>"
  "<packing><property name=\"expand\">False</property><property name=\"pos"
  "ition\">1</property></packing></child></object><packing><property name="
  "\"position\">0</property></packing></child><child><object class=\"GtkHB"
  "ox\" id=\"output-box\"><property name=\"visible\">True</property><prope"
  "rty name=\"spacing\">12</property><child><object class=\"GtkLabel\" id="
  "\"label13\"><property name=\"visible\">True</property><property name=\""
  "xalign\">0</property><property name=\"label\" translatable=\"yes\">O_ut"
  "put:</property><property name=\"use_underline\">True</property><propert"
  "y name=\"mnemonic_widget\">output-name</property></object><packing><pro"
  "perty name=\"expand\">False</property><property name=\"position\">0</pr"
  "operty></packing></child><child><object class=\"GtkComboBox\" id=\"outp"
  "ut-name\"><property name=\"visible\">True</property><property name=\"mo"
  "del\">output-store</property><child><object class=\"GtkCellRendererText"
  "\" id=\"cellrenderertext3\"/><attributes><attribute name=\"text\">1</at"
  "tribute></attributes></child></object><packing><property name=\"expand\""
  ">False</property><property name=\"position\">1</property></packing></ch"
  "ild></object><packing><property name=\"position\">1</property></packing"
  "></child><child><object class=\"GtkCheckButton\" id=\"span-monitors\"><"
  "property name=\"label\" translatable=\"yes\">Span mo_nitors</property><"
  "property name=\"visible\">True</property><property name=\"can_focus\">T"
  "rue</property><property name=\"receives_default\">False</property><prop"
  "erty name=\"tooltip_text\" translatable=\"yes\">Select this option to e"
  "xtend the panel over multiple monitors.</property><property name=\"use_"
  "underline\">True</property><property name=\"draw_indicator\">True</prop"
  "erty></object><packing><property name=\"position\">2</property></packin"
  "g></child><child><object class=\"GtkCheckButton\" id=\"position-locked\""
  "><property name=\"label\" translatable=\"yes\">_Lock panel</property><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Tr"
  "ue</property><property name=\"receives_default\">False</property><prope"
  "rty name=\"tooltip_text\" translatable=\"yes\">Select this option to hi"
  "de the handles of the panel and lock its position.</property><property "
  "name=\"use_underline\">True</property><property name=\"draw_indicator\""
  ">True</property></object><packing><property name=\"position\">3</proper"
  "ty></packing></child><child><object class=\"GtkHBox\" id=\"hbox6\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><property name=\"spacing\">12</property><child><object clas"
  "s=\"GtkLabel\" id=\"label20\"><property name=\"visible\">True</property"
  "><property name=\"can_focus\">False</property><property name=\"xalign\""
  ">0</property><property name=\"label\" translatable=\"yes\">Automaticall"
  "y hide the panel:</property><property name=\"use_underline\">True</prop"
  "erty><property name=\"mnemonic_widget\">mode</property></object><packin"
  "g><property name=\"expand\">False</property><property name=\"fill\">Tru"
  "e</property><property name=\"position\">0</property></packing></child><"
  "child><object class=\"GtkComboBox\" id=\"autohide-behavior\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">False</pro"
  "perty><property name=\"model\">autohide-behavior-store</property><child"
  "><object class=\"GtkCellRendererText\" id=\"cellrenderertext5\"/><attri"
  "butes><attribute name=\"text\">0</attribute></attributes></child></obje"
  "ct><packing><property name=\"expand\">False</property><property name=\""
  "fill\">True</property><property name=\"position\">1</property></packing"
  "></child></object><packing><property name=\"expand\">True</property><pr"
  "operty name=\"fill\">True</property><property name=\"position\">4</prop"
  "erty></packing></child><child><object class=\"GtkCheckButton\" id=\"dis"
  "able-struts\"><property name=\"label\" translatable=\"yes\">Don\'t _res"
  "erve space on borders</property><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">True</property><property name=\"receive"
  "s_default\">False</property><property name=\"tooltip_text\" translatabl"
  "e=\"yes\">Select this option if you want maximized windows to cover the"
  " area behind the panel. This only works when the panel is attached to a"
  " screen edge.</property><property name=\"use_underline\">True</property"
  "><property name=\"draw_indicator\">True</property></object><packing><pr"
  "operty name=\"position\">5</property></packing></child></object></child"
  "></object></child><child type=\"label\"><object class=\"GtkLabel\" id=\""
  "label2\"><property name=\"visible\">True</property><property name=\"lab"
  "el\" translatable=\"yes\">General</property><attributes><attribute name"
  "=\"weight\" value=\"bold\"/></attributes></object></child></object><pac"
  "king><property name=\"expand\">False</property><property name=\"positio"
  "n\">0</property></packing></child><child><object class=\"GtkFrame\" id="
  "\"frame2\"><property name=\"visible\">True</property><property name=\"l"
  "abel_xalign\">0</property><property name=\"shadow_type\">none</property"
  "><child><object class=\"GtkAlignment\" id=\"alignment2\"><property name"
  "=\"visible\">True</property><property name=\"left_padding\">12</propert"
  "y><child><object class=\"GtkTable\" id=\"table1\"><property name=\"visi"
  "ble\">True</property><property name=\"border_width\">6</property><prope"
  "rty name=\"n_rows\">4</property><property name=\"n_columns\">2</propert"
  "y><property name=\"column_spacing\">12</property><property name=\"row_s"
  "pacing\">6</property><child><object class=\"GtkLabel\" id=\"label3\"><p"
  "roperty name=\"visible\">True</property><property name=\"xalign\">0</pr"
  "operty><property name=\"label\" translatable=\"yes\">Row _Size (pixels)"
  ":</property><property name=\"use_underline\">True</property><property n"
  "ame=\"mnemonic_widget\">size-scale</property></object><packing><propert"
  "y name=\"x_options\">GTK_FILL</property></packing></child><child><objec"
  "t class=\"GtkLabel\" id=\"label4\"><property name=\"visible\">True</pro"
  "perty><property name=\"xalign\">0</property><property name=\"label\" tr"
  "anslatable=\"yes\">L_ength (%):</property><property name=\"use_underlin"
  "e\">True</property><property name=\"mnemonic_widget\">length-scale</pro"
  "perty></object><packing><property name=\"top_attach\">2</property><prop"
  "erty name=\"bottom_attach\">3</property><property name=\"x_options\">GT"
  "K_FILL</property></packing></child><child><object class=\"GtkLabel\" id"
  "=\"label18\"><property name=\"visible\">True</property><property name=\""
  "xalign\">0</property><property name=\"label\" translatable=\"yes\">Num_"
  "ber of rows:</property><property name=\"use_underline\">True</property>"
  "<property name=\"mnemonic_widget\">nrows-scale</property></object><pack"
  "ing><property name=\"top_attach\">1</property><property name=\"bottom_a"
  "ttach\">2</property><property name=\"x_options\">GTK_FILL</property></p"
  "acking></child><child><object class=\"GtkHScale\" id=\"length-scale\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">T"
  "rue</property><property name=\"update_policy\">discontinuous</property>"
  "<property name=\"adjustment\">length</property><property name=\"digits\""
  ">0</property><property name=\"value_pos\">right</property></object><pac"
  "king><property name=\"left_attach\">1</property><property name=\"right_"
  "attach\">2</property><property name=\"top_attach\">2</property><propert"
  "y name=\"bottom_attach\">3</property></packing></child><child><object c"
  "lass=\"GtkHScale\" id=\"size-scale\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">True</property><property name=\"up"
  "date_policy\">discontinuous</property><property name=\"adjustment\">siz"
  "e</property><property name=\"digits\">0</property><property name=\"valu"
  "e_pos\">right</property></object><packing><property name=\"left_attach\""
  ">1</property><property name=\"right_attach\">2</property></packing></ch"
  "ild><child><object class=\"GtkHScale\" id=\"nrows-scale\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">True</propert"
  "y><property name=\"update_policy\">discontinuous</property><property na"
  "me=\"adjustment\">nrows</property><property name=\"digits\">0</property"
  "><property name=\"value_pos\">right</property></object><packing><proper"
  "ty name=\"left_attach\">1</property><property name=\"right_attach\">2</"
  "property><property name=\"top_attach\">1</property><property name=\"bot"
  "tom_attach\">2</property></packing></child><child><object class=\"GtkCh"
  "eckButton\" id=\"length-adjust\"><property name=\"label\" translatable="
  "\"yes\">A_utomatically increase the length</property><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">True</property><pr"
  "operty name=\"receives_default\">False</property><property name=\"toolt"
  "ip_text\" translatable=\"yes\">Select this option to automatically incr"
  "ease the length of the panel if the plugins request more space.</proper"
  "ty><property name=\"use_underline\">True</property><property name=\"dra"
  "w_indicator\">True</property></object><packing><property name=\"right_a"
  "ttach\">2</property><property name=\"top_attach\">3</property><property"
  " name=\"bottom_attach\">4</property></packing></child></object></child>"
  "</object></child><child type=\"label\"><object class=\"GtkLabel\" id=\""
  "label5\"><property name=\"visible\">True</property><property name=\"lab"
  "el\" translatable=\"yes\" comments=\"I18N: name of the section (frame) "
  "in the panel preferences where the user can define the length and size "
  "of the panel\">Measurements</property><attributes><attribute name=\"wei"
  "ght\" value=\"bold\"/></attributes></object></child></object><packing><"
  "property name=\"expand\">False</property><property name=\"position\">1<"
  "/property></packing></child></object></child><child type=\"tab\"><objec"
  "t class=\"GtkLabel\" id=\"label6\"><property name=\"visible\">True</pro"
  "perty><property name=\"label\" translatable=\"yes\">D_isplay</property>"
  "<property name=\"use_underline\">True</property></object><packing><prop"
  "erty name=\"tab_fill\">False</property></packing></child><child><object"
  " class=\"GtkVBox\" id=\"vbox7\"><property name=\"visible\">True</proper"
  "ty><property name=\"border_width\">6</property><property name=\"orienta"
  "tion\">vertical</property><property name=\"spacing\">6</property><child"
  "><object class=\"GtkFrame\" id=\"frame3\"><property name=\"visible\">Tr"
  "ue</property><property name=\"label_xalign\">0</property><property name"
  "=\"shadow_type\">none</property><child><object class=\"GtkAlignment\" i"
  "d=\"alignment3\"><property name=\"visible\">True</property><property na"
  "me=\"left_padding\">12</property><child><object class=\"GtkVBox\" id=\""
  "vbox4\"><property name=\"visible\">True</property><property name=\"bord"
  "er_width\">6</property><property name=\"orientation\">vertical</propert"
  "y><property name=\"spacing\">6</property><child><object class=\"GtkHBox"
  "\" id=\"hbox2\"><property name=\"visible\">True</property><property nam"
  "e=\"spacing\">12</property><child><object class=\"GtkLabel\" id=\"label"
  "7\"><property name=\"visible\">True</property><property name=\"xalign\""
  ">0</property><property name=\"label\" translatable=\"yes\">_Style:</pro"
  "perty><property name=\"use_underline\">True</property><property name=\""
  "mnemonic_widget\">background-style</property></object><packing><propert"
  "y name=\"expand\">False</property><property name=\"position\">0</proper"
  "ty></packing></child><child><object class=\"GtkComboBox\" id=\"backgrou"
  "nd-style\"><property name=\"visible\">True</property><property name=\"m"
  "odel\">styles-store</property><child><object class=\"GtkCellRendererTex"
  "t\" id=\"cellrenderertext4\"/><attributes><attribute name=\"text\">0</a"
  "ttribute></attributes></child></object><packing><property name=\"expand"
  "\">False</property><property name=\"position\">1</property></packing></"
  "child></object><packing><property name=\"position\">0</property></packi"
  "ng></child><child><object class=\"GtkHBox\" id=\"bg-alpha-box\"><proper"
  "ty name=\"visible\">True</property><property name=\"spacing\">12</prope"
  "rty><child><object class=\"GtkLabel\" id=\"label15\"><property name=\"v"
  "isible\">True</property><property name=\"xalign\">0</property><property"
  " name=\"label\" translatable=\"yes\">_Alpha:</property><property name=\""
  "use_underline\">True</property><property name=\"mnemonic_widget\">bg-al"
  "pha-scale</property></object><packing><property name=\"expand\">False</"
  "property><property name=\"position\">0</property></packing></child><chi"
  "ld><object class=\"GtkHScale\" id=\"bg-alpha-scale\"><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">True</property><pr"
  "operty name=\"tooltip_text\" translatable=\"yes\">Alpha value of the pa"
  "nel background, with 0 being fully transparent and 100 fully opaque.</p"
  "roperty><property name=\"adjustment\">background-alpha</property><prope"
  "rty name=\"digits\">0</property><property name=\"value_pos\">right</pro"
  "perty></object><packing><property name=\"position\">1</property></packi"
  "ng></child></object><packing><property name=\"position\">1</property></"
  "packing></child><child><object class=\"GtkHBox\" id=\"bg-color-box\"><p"
  "roperty name=\"visible\">True</property><property name=\"spacing\">12</"
  "property><child><object class=\"GtkLabel\" id=\"label16\"><property nam"
  "e=\"visible\">True</property><property name=\"xalign\">0</property><pro"
  "perty name=\"label\" translatable=\"yes\">C_olor:</property><property n"
  "ame=\"use_underline\">True</property><property name=\"mnemonic_widget\""
  ">background-color</property></object><packing><property name=\"expand\""
  ">False</property><property name=\"position\">0</property></packing></ch"
  "ild><child><object class=\"GtkColorButton\" id=\"background-color\"><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Tru"
  "e</property><property name=\"receives_default\">True</property><propert"
  "y name=\"title\" translatable=\"yes\">Pick a Panel Color</property><pro"
  "perty name=\"color\">#000000000000</property></object><packing><propert"
  "y name=\"expand\">False</property><property name=\"position\">1</proper"
  "ty></packing></child></object><packing><property name=\"position\">2</p"
  "roperty></packing></child><child><object class=\"GtkHBox\" id=\"bg-imag"
  "e-box\"><property name=\"visible\">True</property><property name=\"spac"
  "ing\">12</property><child><object class=\"GtkLabel\" id=\"label19\"><pr"
  "operty name=\"visible\">True</property><property name=\"xalign\">0</pro"
  "perty><property name=\"label\" translatable=\"yes\">_File:</property><p"
  "roperty name=\"use_underline\">True</property><property name=\"mnemonic"
  "_widget\">background-image</property></object><packing><property name=\""
  "expand\">False</property><property name=\"position\">0</property></pack"
  "ing></child><child><object class=\"GtkFileChooserButton\" id=\"backgrou"
  "nd-image\"><property name=\"visible\">True</property><property name=\"t"
  "itle\" translatable=\"yes\">Select A Background Image</property></objec"
  "t><packing><property name=\"position\">1</property></packing></child></"
  "object><packing><property name=\"position\">3</property></packing></chi"
  "ld></object></child></object></child><child type=\"label\"><object clas"
  "s=\"GtkLabel\" id=\"label8\"><property name=\"visible\">True</property>"
  "<property name=\"label\" translatable=\"yes\">Background</property><att"
  "ributes><attribute name=\"weight\" value=\"bold\"/></attributes></objec"
  "t></child></object><packing><property name=\"expand\">False</property><"
  "property name=\"position\">0</property></packing></child><child><object"
  " class=\"GtkFrame\" id=\"composited\"><property name=\"visible\">True</"
  "property><property name=\"label_xalign\">0</property><property name=\"s"
  "hadow_type\">none</property><child><object class=\"GtkAlignment\" id=\""
  "alignment4\"><property name=\"visible\">True</property><property name=\""
  "left_padding\">12</property><child><object class=\"GtkTable\" id=\"tabl"
  "e2\"><property name=\"visible\">True</property><property name=\"border_"
  "width\">6</property><property name=\"n_rows\">2</property><property nam"
  "e=\"n_columns\">2</property><property name=\"column_spacing\">12</prope"
  "rty><property name=\"row_spacing\">6</property><child><object class=\"G"
  "tkLabel\" id=\"label9\"><property name=\"visible\">True</property><prop"
  "erty name=\"xalign\">0</property><property name=\"label\" translatable="
  "\"yes\" comments=\"I18N: label for the enter transparency slider\">_Ent"
  "er:</property><property name=\"use_underline\">True</property><property"
  " name=\"mnemonic_widget\">enter-opacity-scale</property></object><packi"
  "ng><property name=\"x_options\">GTK_FILL</property></packing></child><c"
  "hild><object class=\"GtkLabel\" id=\"label10\"><property name=\"visible"
  "\">True</property><property name=\"xalign\">0</property><property name="
  "\"label\" translatable=\"yes\" comments=\"I18N: label for the leave tra"
  "nsparency slider\">_Leave:</property><property name=\"use_underline\">T"
  "rue</property><property name=\"mnemonic_widget\">leave-opacity-scale</p"
  "roperty></object><packing><property name=\"top_attach\">1</property><pr"
  "operty name=\"bottom_attach\">2</property><property name=\"x_options\">"
  "GTK_FILL</property></packing></child><child><object class=\"GtkHScale\""
  " id=\"enter-opacity-scale\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">True</property><property name=\"tooltip_tex"
  "t\" translatable=\"yes\">Transparency when the pointer is hovering over"
  " the panel, with 0 being fully transparent and 100 fully opaque.</prope"
  "rty><property name=\"adjustment\">enter-opacity</property><property nam"
  "e=\"digits\">0</property><property name=\"value_pos\">right</property><"
  "/object><packing><property name=\"left_attach\">1</property><property n"
  "ame=\"right_attach\">2</property></packing></child><child><object class"
  "=\"GtkHScale\" id=\"leave-opacity-scale\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">True</property><property name"
  "=\"tooltip_text\" translatable=\"yes\">Transparency when the pointer is"
  " not hovering over the panel, with 0 being fully transparent and 100 fu"
  "lly opaque.</property><property name=\"adjustment\">leave-opacity</prop"
  "erty><property name=\"digits\">0</property><property name=\"value_pos\""
  ">right</property></object><packing><property name=\"left_attach\">1</pr"
  "operty><property name=\"right_attach\">2</property><property name=\"top"
  "_attach\">1</property><property name=\"bottom_attach\">2</property></pa"
  "cking></child></object></child></object></child><child type=\"label\"><"
  "object class=\"GtkLabel\" id=\"label11\"><property name=\"visible\">Tru"
  "e</property><property name=\"label\" translatable=\"yes\">Opacity</prop"
  "erty><attributes><attribute name=\"weight\" value=\"bold\"/></attribute"
  "s></object></child></object><packing><property name=\"expand\">False</p"
  "roperty><property name=\"position\">1</property></packing></child><chil"
  "d><object class=\"GtkAlignment\" id=\"composited-info\"><property name="
  "\"visible\">True</property><property name=\"can_focus\">False</property"
  "><property name=\"xalign\">0</property><property name=\"yalign\">1</pro"
  "perty><property name=\"xscale\">0</property><property name=\"yscale\">0"
  "</property><child><object class=\"GtkHBox\" id=\"hbox5\"><property name"
  "=\"visible\">True</property><property name=\"can_focus\">False</propert"
  "y><property name=\"spacing\">6</property><child><object class=\"GtkImag"
  "e\" id=\"image9\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">False</property><property name=\"stock\">gtk-info</pr"
  "operty><property name=\"icon-size\">5</property></object><packing><prop"
  "erty name=\"expand\">False</property><property name=\"fill\">True</prop"
  "erty><property name=\"position\">0</property></packing></child><child><"
  "object class=\"GtkLabel\" id=\"label17\"><property name=\"visible\">Tru"
  "e</property><property name=\"can_focus\">False</property><property name"
  "=\"xalign\">0</property><property name=\"label\" translatable=\"yes\">E"
  "nable compositing in the window manager for opacity settings in the pan"
  "el.</property><property name=\"wrap\">True</property><property name=\"w"
  "idth_chars\">0</property></object><packing><property name=\"expand\">Tr"
  "ue</property><property name=\"fill\">True</property><property name=\"po"
  "sition\">1</property></packing></child></object></child></object><packi"
  "ng><property name=\"expand\">True</property><property name=\"fill\">Tru"
  "e</property><property name=\"position\">2</property></packing></child><"
  "/object><packing><property name=\"position\">1</property></packing></ch"
  "ild><child type=\"tab\"><object class=\"GtkLabel\" id=\"label12\"><prop"
  "erty name=\"visible\">True</property><property name=\"label\" translata"
  "ble=\"yes\">Appeara_nce</property><property name=\"use_underline\">True"
  "</property></object><packing><property name=\"position\">1</property><p"
  "roperty name=\"tab_fill\">False</property></packing></child><child><obj"
  "ect class=\"GtkHBox\" id=\"hbox4\"><property name=\"visible\">True</pro"
  "perty><property name=\"border_width\">6</property><property name=\"spac"
  "ing\">6</property><child><object class=\"GtkScrolledWindow\" id=\"scrol"
  "ledwindow3\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"hscrollbar_policy\">automat"
  "ic</property><property name=\"vscrollbar_policy\">automatic</property><"
  "property name=\"shadow_type\">etched-in</property><child><object class="
  "\"GtkTreeView\" id=\"item-treeview\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">True</property><property name=\"he"
  "aders_visible\">False</property><property name=\"rules_hint\">True</pro"
  "perty><property name=\"enable_search\">False</property></object></child"
  "></object><packing><property name=\"position\">0</property></packing></"
  "child><child><object class=\"GtkVBox\" id=\"vbox6\"><property name=\"vi"
  "sible\">True</property><property name=\"orientation\">vertical</propert"
  "y><property name=\"spacing\">6</property><child><object class=\"GtkButt"
  "on\" id=\"item-up\"><property name=\"visible\">True</property><property"
  " name=\"sensitive\">False</property><property name=\"can_focus\">True</"
  "property><property name=\"receives_default\">True</property><property n"
  "ame=\"tooltip_text\" translatable=\"yes\">Move currently selected item "
  "up by one row</property><child><object class=\"GtkImage\" id=\"image3\""
  "><property name=\"visible\">True</property><property name=\"stock\">gtk"
  "-go-up</property></object></child></object><packing><property name=\"ex"
  "pand\">False</property><property name=\"position\">0</property></packin"
  "g></child><child><object class=\"GtkButton\" id=\"item-down\"><property"
  " name=\"visible\">True</property><property name=\"sensitive\">False</pr"
  "operty><property name=\"can_focus\">True</property><property name=\"rec"
  "eives_default\">True</property><property name=\"tooltip_text\" translat"
  "able=\"yes\">Move currently selected item down by one row</property><ch"
  "ild><object class=\"GtkImage\" id=\"image4\"><property name=\"visible\""
  ">True</property><property name=\"stock\">gtk-go-down</property></object"
  "></child></object><packing><property name=\"expand\">False</property><p"
  "roperty name=\"position\">1</property></packing></child><child><object "
  "class=\"GtkButton\" id=\"item-add\"><property name=\"visible\">True</pr"
  "operty><property name=\"sensitive\">False</property><property name=\"ca"
  "n_focus\">True</property><property name=\"receives_default\">True</prop"
  "erty><property name=\"tooltip_text\" translatable=\"yes\">Add new item "
  "to this panel</property><child><object class=\"GtkImage\" id=\"image5\""
  "><property name=\"visible\">True</property><property name=\"stock\">gtk"
  "-add</property></object></child></object><packing><property name=\"expa"
  "nd\">False</property><property name=\"position\">2</property></packing>"
  "</child><child><object class=\"GtkButton\" id=\"item-remove\"><property"
  " name=\"visible\">True</property><property name=\"sensitive\">False</pr"
  "operty><property name=\"can_focus\">True</property><property name=\"rec"
  "eives_default\">True</property><property name=\"tooltip_text\" translat"
  "able=\"yes\">Remove currently selected item</property><child><object cl"
  "ass=\"GtkImage\" id=\"image6\"><property name=\"visible\">True</propert"
  "y><property name=\"stock\">gtk-remove</property></object></child></obje"
  "ct><packing><property name=\"expand\">False</property><property name=\""
  "position\">3</property></packing></child><child><object class=\"GtkButt"
  "on\" id=\"item-properties\"><property name=\"visible\">True</property><"
  "property name=\"sensitive\">False</property><property name=\"can_focus\""
  ">True</property><property name=\"receives_default\">True</property><pro"
  "perty name=\"tooltip_text\" translatable=\"yes\">Edit the currently sel"
  "ected item</property><child><object class=\"GtkImage\" id=\"image7\"><p"
  "roperty name=\"visible\">True</property><property name=\"stock\">gtk-pr"
  "operties</property></object></child></object><packing><property name=\""
  "expand\">False</property><property name=\"position\">4</property></pack"
  "ing></child><child><object class=\"GtkButton\" id=\"item-about\"><prope"
  "rty name=\"visible\">True</property><property name=\"sensitive\">False<"
  "/property><property name=\"can_focus\">True</property><property name=\""
  "receives_default\">True</property><property name=\"tooltip_text\" trans"
  "latable=\"yes\">Show about information of the currently selected item</"
  "property><child><object class=\"GtkImage\" id=\"image8\"><property name"
  "=\"visible\">True</property><property name=\"stock\">gtk-about</propert"
  "y></object></child></object><packing><property name=\"expand\">False</p"
  "roperty><property name=\"position\">5</property></packing></child></obj"
  "ect><packing><property name=\"expand\">False</property><property name=\""
  "position\">1</property></packing></child></object><packing><property na"
  "me=\"position\">2</property></packing></child><child type=\"tab\"><obje"
  "ct class=\"GtkLabel\" id=\"label14\"><property name=\"visible\">True</p"
  "roperty><property name=\"label\" translatable=\"yes\">Ite_ms</property>"
  "<property name=\"use_underline\">True</property></object><packing><prop"
  "erty name=\"position\">2</property><property name=\"tab_fill\">False</p"
  "roperty></packing></child></object><packing><property name=\"position\""
  ">2</property></packing></child></object><packing><property name=\"posit"
  "ion\">1</property></packing></child><child internal-child=\"action_area"
  "\"><object class=\"GtkHButtonBox\" id=\"dialog-action_area1\"><property"
  " name=\"visible\">True</property><property name=\"layout_style\">end</p"
  "roperty><child><object class=\"GtkButton\" id=\"button-close\"><propert"
  "y name=\"label\">gtk-close</property><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">True</property><property name=\"re"
  "ceives_default\">True</property><property name=\"use_stock\">True</prop"
  "erty></object><packing><property name=\"expand\">False</property><prope"
  "rty name=\"fill\">False</property><property name=\"position\">0</proper"
  "ty></packing></child><child><object class=\"GtkButton\" id=\"button-hel"
  "p\"><property name=\"label\">gtk-help</property><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">True</property><propert"
  "y name=\"receives_default\">True</property><property name=\"use_stock\""
  ">True</property></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"fill\">False</property><property name=\"position\""
  ">1</property><property name=\"secondary\">True</property></packing></ch"
  "ild></object><packing><property name=\"expand\">False</property><proper"
  "ty name=\"pack_type\">end</property><property name=\"position\">0</prop"
  "erty></packing></child></object></child><action-widgets><action-widget "
  "response=\"0\">button-close</action-widget><action-widget response=\"1\""
  ">button-help</action-widget></action-widgets></object></interface>"
};

static const unsigned panel_preferences_dialog_ui_length = 33977u;

