/* automatically generated from separator-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (separator_dialog_ui)
#endif
#ifdef __GNUC__
static const char separator_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char separator_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\"?><interface><requires lib=\"gtk+\" version=\"2.24"
  "\"/><object class=\"XfceTitledDialog\" id=\"dialog\"><property name=\"t"
  "itle\" translatable=\"yes\">Separator</property><property name=\"icon_n"
  "ame\">gtk-properties</property><property name=\"type_hint\">normal</pro"
  "perty><property name=\"has_separator\">False</property><child internal-"
  "child=\"vbox\"><object class=\"GtkVBox\" id=\"dialog-vbox2\"><property "
  "name=\"visible\">True</property><property name=\"orientation\">vertical"
  "</property><property name=\"spacing\">2</property><child><object class="
  "\"GtkFrame\" id=\"frame1\"><property name=\"visible\">True</property><p"
  "roperty name=\"border_width\">6</property><property name=\"label_xalign"
  "\">0</property><property name=\"shadow_type\">none</property><child><ob"
  "ject class=\"GtkAlignment\" id=\"alignment1\"><property name=\"visible\""
  ">True</property><property name=\"left_padding\">12</property><child><ob"
  "ject class=\"GtkVBox\" id=\"vbox3\"><property name=\"visible\">True</pr"
  "operty><property name=\"border_width\">6</property><property name=\"ori"
  "entation\">vertical</property><property name=\"spacing\">6</property><c"
  "hild><object class=\"GtkHBox\" id=\"hbox1\"><property name=\"visible\">"
  "True</property><property name=\"spacing\">12</property><child><object c"
  "lass=\"GtkLabel\" id=\"label2\"><property name=\"visible\">True</proper"
  "ty><property name=\"label\" translatable=\"yes\">_Style:</property><pro"
  "perty name=\"use_underline\">True</property><property name=\"mnemonic_w"
  "idget\">style</property></object><packing><property name=\"expand\">Fal"
  "se</property><property name=\"position\">0</property></packing></child>"
  "<child><object class=\"GtkComboBox\" id=\"style\"><property name=\"visi"
  "ble\">True</property><property name=\"model\">style-model</property><ch"
  "ild><object class=\"GtkCellRendererText\" id=\"cellrenderertext1\"/><at"
  "tributes><attribute name=\"text\">0</attribute></attributes></child></o"
  "bject><packing><property name=\"position\">1</property></packing></chil"
  "d></object><packing><property name=\"position\">0</property></packing><"
  "/child><child><object class=\"GtkCheckButton\" id=\"expand\"><property "
  "name=\"label\" translatable=\"yes\">_Expand</property><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"receives_default\">False</property><property name=\"use_"
  "underline\">True</property><property name=\"draw_indicator\">True</prop"
  "erty></object><packing><property name=\"position\">1</property></packin"
  "g></child></object></child></object></child><child type=\"label\"><obje"
  "ct class=\"GtkLabel\" id=\"label1\"><property name=\"visible\">True</pr"
  "operty><property name=\"label\" translatable=\"yes\">Appearance</proper"
  "ty><attributes><attribute name=\"weight\" value=\"bold\"/></attributes>"
  "</object></child></object><packing><property name=\"expand\">False</pro"
  "perty><property name=\"position\">1</property></packing></child><child "
  "internal-child=\"action_area\"><object class=\"GtkHButtonBox\" id=\"dia"
  "log-action_area2\"><property name=\"visible\">True</property><property "
  "name=\"layout_style\">end</property><child><object class=\"GtkButton\" "
  "id=\"close-button\"><property name=\"label\">gtk-close</property><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">True</"
  "property><property name=\"receives_default\">True</property><property n"
  "ame=\"use_stock\">True</property></object><packing><property name=\"exp"
  "and\">False</property><property name=\"fill\">False</property><property"
  " name=\"position\">0</property></packing></child><child><object class=\""
  "GtkButton\" id=\"help-button\"><property name=\"label\">gtk-help</prope"
  "rty><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">True</property><property name=\"receives_default\">True</property><"
  "property name=\"use_stock\">True</property></object><packing><property "
  "name=\"expand\">False</property><property name=\"fill\">False</property"
  "><property name=\"position\">1</property><property name=\"secondary\">T"
  "rue</property></packing></child></object><packing><property name=\"expa"
  "nd\">False</property><property name=\"pack_type\">end</property><proper"
  "ty name=\"position\">0</property></packing></child></object></child><ac"
  "tion-widgets><action-widget response=\"0\">close-button</action-widget>"
  "<action-widget response=\"0\">help-button</action-widget></action-widge"
  "ts></object><object class=\"GtkListStore\" id=\"style-model\"><columns>"
  "<column type=\"gchararray\"/></columns><data><row><col id=\"0\" transla"
  "table=\"yes\">Transparent</col></row><row><col id=\"0\" translatable=\""
  "yes\">Separator</col></row><row><col id=\"0\" translatable=\"yes\">Hand"
  "le</col></row><row><col id=\"0\" translatable=\"yes\">Dots</col></row><"
  "/data></object></interface>"
};

static const unsigned separator_dialog_ui_length = 4483u;

