/* automatically generated from applicationsmenu-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (applicationsmenu_dialog_ui)
#endif
#ifdef __GNUC__
static const char applicationsmenu_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char applicationsmenu_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\"?><interface><requires lib=\"gtk+\" version=\"2.24"
  "\"/><object class=\"XfceTitledDialog\" id=\"dialog\"><property name=\"t"
  "itle\" translatable=\"yes\">Applications Menu</property><property name="
  "\"icon_name\">gtk-properties</property><property name=\"type_hint\">nor"
  "mal</property><child internal-child=\"vbox\"><object class=\"GtkVBox\" "
  "id=\"dialog-vbox2\"><property name=\"visible\">True</property><property"
  " name=\"orientation\">vertical</property><property name=\"spacing\">2</"
  "property><child><object class=\"GtkVBox\" id=\"vbox1\"><property name=\""
  "visible\">True</property><property name=\"border_width\">6</property><p"
  "roperty name=\"orientation\">vertical</property><property name=\"spacin"
  "g\">6</property><child><object class=\"GtkFrame\" id=\"frame3\"><proper"
  "ty name=\"visible\">True</property><property name=\"label_xalign\">0</p"
  "roperty><property name=\"shadow_type\">none</property><child><object cl"
  "ass=\"GtkAlignment\" id=\"alignment3\"><property name=\"visible\">True<"
  "/property><property name=\"left_padding\">12</property><child><object c"
  "lass=\"GtkTable\" id=\"table1\"><property name=\"visible\">True</proper"
  "ty><property name=\"border_width\">6</property><property name=\"n_rows\""
  ">6</property><property name=\"n_columns\">2</property><property name=\""
  "column_spacing\">12</property><property name=\"row_spacing\">6</propert"
  "y><child><object class=\"GtkCheckButton\" id=\"show-generic-names\"><pr"
  "operty name=\"label\" translatable=\"yes\">Show generic application n_a"
  "mes</property><property name=\"visible\">True</property><property name="
  "\"can_focus\">True</property><property name=\"receives_default\">False<"
  "/property><property name=\"tooltip_text\" translatable=\"yes\">Select t"
  "his option to show the generic application name in the menu, for exampl"
  "e \"File Manager\" instead of \"Thunar\"</property><property name=\"use"
  "_underline\">True</property><property name=\"draw_indicator\">True</pro"
  "perty></object><packing><property name=\"right_attach\">2</property></p"
  "acking></child><child><object class=\"GtkCheckButton\" id=\"show-menu-i"
  "cons\"><property name=\"label\" translatable=\"yes\">Show ic_ons in men"
  "u</property><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"receives_default\">False</p"
  "roperty><property name=\"use_underline\">True</property><property name="
  "\"draw_indicator\">True</property></object><packing><property name=\"ri"
  "ght_attach\">2</property><property name=\"top_attach\">1</property><pro"
  "perty name=\"bottom_attach\">2</property></packing></child><child><obje"
  "ct class=\"GtkCheckButton\" id=\"show-button-title\"><property name=\"l"
  "abel\" translatable=\"yes\">_Show button title</property><property name"
  "=\"visible\">True</property><property name=\"can_focus\">True</property"
  "><property name=\"receives_default\">False</property><property name=\"u"
  "se_underline\">True</property><property name=\"draw_indicator\">True</p"
  "roperty></object><packing><property name=\"right_attach\">2</property><"
  "property name=\"top_attach\">3</property><property name=\"bottom_attach"
  "\">4</property></packing></child><child><object class=\"GtkLabel\" id=\""
  "label2\"><property name=\"visible\">True</property><property name=\"xal"
  "ign\">0</property><property name=\"label\" translatable=\"yes\">Button "
  "_title:</property><property name=\"use_underline\">True</property><prop"
  "erty name=\"mnemonic_widget\">button-title</property></object><packing>"
  "<property name=\"top_attach\">4</property><property name=\"bottom_attac"
  "h\">5</property><property name=\"x_options\">GTK_FILL</property></packi"
  "ng></child><child><object class=\"GtkEntry\" id=\"button-title\"><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">True</"
  "property><property name=\"invisible_char\">&#x2022;</property></object>"
  "<packing><property name=\"left_attach\">1</property><property name=\"ri"
  "ght_attach\">2</property><property name=\"top_attach\">4</property><pro"
  "perty name=\"bottom_attach\">5</property></packing></child><child><obje"
  "ct class=\"GtkLabel\" id=\"label4\"><property name=\"visible\">True</pr"
  "operty><property name=\"xalign\">0</property><property name=\"label\" t"
  "ranslatable=\"yes\">_Icon:</property><property name=\"use_underline\">T"
  "rue</property><property name=\"mnemonic_widget\">icon-button</property>"
  "</object><packing><property name=\"top_attach\">5</property><property n"
  "ame=\"bottom_attach\">6</property><property name=\"x_options\">GTK_FILL"
  "</property></packing></child><child><object class=\"GtkAlignment\" id=\""
  "alignment4\"><property name=\"visible\">True</property><property name=\""
  "xalign\">0</property><property name=\"xscale\">0</property><property na"
  "me=\"yscale\">0</property><child><object class=\"GtkButton\" id=\"icon-"
  "button\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">True</property><property name=\"receives_default\">True</prope"
  "rty><child><placeholder/></child></object></child></object><packing><pr"
  "operty name=\"left_attach\">1</property><property name=\"right_attach\""
  ">2</property><property name=\"top_attach\">5</property><property name=\""
  "bottom_attach\">6</property></packing></child><child><object class=\"Gt"
  "kCheckButton\" id=\"show-tooltips\"><property name=\"label\" translatab"
  "le=\"yes\">Show application d_escription in tooltip</property><property"
  " name=\"visible\">True</property><property name=\"can_focus\">True</pro"
  "perty><property name=\"receives_default\">False</property><property nam"
  "e=\"use_underline\">True</property><property name=\"image_position\">ri"
  "ght</property><property name=\"draw_indicator\">True</property></object"
  "><packing><property name=\"right_attach\">2</property><property name=\""
  "top_attach\">2</property><property name=\"bottom_attach\">3</property><"
  "/packing></child></object></child></object></child><child type=\"label\""
  "><object class=\"GtkLabel\" id=\"label1\"><property name=\"visible\">Tr"
  "ue</property><property name=\"label\" translatable=\"yes\">Appearance</"
  "property><attributes><attribute name=\"weight\" value=\"bold\"/></attri"
  "butes></object></child></object><packing><property name=\"expand\">Fals"
  "e</property><property name=\"position\">0</property></packing></child><"
  "child><object class=\"GtkFrame\" id=\"frame1\"><property name=\"visible"
  "\">True</property><property name=\"label_xalign\">0</property><property"
  " name=\"shadow_type\">none</property><child><object class=\"GtkAlignmen"
  "t\" id=\"alignment1\"><property name=\"visible\">True</property><proper"
  "ty name=\"left_padding\">12</property><child><object class=\"GtkVBox\" "
  "id=\"vbox2\"><property name=\"visible\">True</property><property name=\""
  "border_width\">6</property><property name=\"orientation\">vertical</pro"
  "perty><property name=\"spacing\">6</property><child><object class=\"Gtk"
  "HBox\" id=\"hbox1\"><property name=\"visible\">True</property><property"
  " name=\"spacing\">12</property><child><object class=\"GtkRadioButton\" "
  "id=\"use-default-menu\"><property name=\"label\" translatable=\"yes\">U"
  "se the _default menu</property><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">True</property><property name=\"receives"
  "_default\">False</property><property name=\"use_underline\">True</prope"
  "rty><property name=\"draw_indicator\">True</property></object><packing>"
  "<property name=\"position\">0</property></packing></child><child><objec"
  "t class=\"GtkButton\" id=\"edit-menu-button\"><property name=\"label\" "
  "translatable=\"yes\">Ed_it Menu</property><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">True</property><property name"
  "=\"receives_default\">True</property><property name=\"image\">image1</p"
  "roperty><property name=\"use_underline\">True</property></object><packi"
  "ng><property name=\"expand\">False</property><property name=\"position\""
  ">1</property></packing></child></object><packing><property name=\"posit"
  "ion\">0</property></packing></child><child><object class=\"GtkRadioButt"
  "on\" id=\"use-custom-menu\"><property name=\"label\" translatable=\"yes"
  "\">Use c_ustom menu file:</property><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">True</property><property name=\"rec"
  "eives_default\">False</property><property name=\"use_underline\">True</"
  "property><property name=\"active\">True</property><property name=\"draw"
  "_indicator\">True</property><property name=\"group\">use-default-menu</"
  "property></object><packing><property name=\"position\">1</property></pa"
  "cking></child><child><object class=\"GtkAlignment\" id=\"alignment5\"><"
  "property name=\"visible\">True</property><property name=\"left_padding\""
  ">22</property><child><object class=\"GtkHBox\" id=\"custom-box\"><prope"
  "rty name=\"visible\">True</property><property name=\"spacing\">12</prop"
  "erty><child><object class=\"GtkLabel\" id=\"label5\"><property name=\"v"
  "isible\">True</property><property name=\"label\" translatable=\"yes\">M"
  "enu _file:</property><property name=\"use_underline\">True</property></"
  "object><packing><property name=\"expand\">False</property><property nam"
  "e=\"position\">0</property></packing></child><child><object class=\"Gtk"
  "FileChooserButton\" id=\"custom-file\"><property name=\"visible\">True<"
  "/property><property name=\"title\" translatable=\"yes\">Select A Menu F"
  "ile</property></object><packing><property name=\"position\">1</property"
  "></packing></child></object></child></object><packing><property name=\""
  "position\">2</property></packing></child></object></child></object></ch"
  "ild><child type=\"label\"><object class=\"GtkLabel\" id=\"label3\"><pro"
  "perty name=\"visible\">True</property><property name=\"label\" translat"
  "able=\"yes\">Menu File</property><attributes><attribute name=\"weight\""
  " value=\"bold\"/></attributes></object></child></object><packing><prope"
  "rty name=\"expand\">False</property><property name=\"position\">1</prop"
  "erty></packing></child></object><packing><property name=\"position\">1<"
  "/property></packing></child><child internal-child=\"action_area\"><obje"
  "ct class=\"GtkHButtonBox\" id=\"dialog-action_area2\"><property name=\""
  "visible\">True</property><property name=\"layout_style\">end</property>"
  "<child><object class=\"GtkButton\" id=\"help-button\"><property name=\""
  "label\">gtk-help</property><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">True</property><property name=\"receives_def"
  "ault\">True</property><property name=\"use_stock\">True</property></obj"
  "ect><packing><property name=\"expand\">False</property><property name=\""
  "fill\">False</property><property name=\"position\">0</property><propert"
  "y name=\"secondary\">True</property></packing></child><child><object cl"
  "ass=\"GtkButton\" id=\"close-button\"><property name=\"label\">gtk-clos"
  "e</property><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"receives_default\">True</pr"
  "operty><property name=\"use_stock\">True</property></object><packing><p"
  "roperty name=\"expand\">False</property><property name=\"fill\">False</"
  "property><property name=\"position\">1</property></packing></child></ob"
  "ject><packing><property name=\"expand\">False</property><property name="
  "\"pack_type\">end</property><property name=\"position\">0</property></p"
  "acking></child></object></child><action-widgets><action-widget response"
  "=\"0\">help-button</action-widget><action-widget response=\"0\">close-b"
  "utton</action-widget></action-widgets></object><object class=\"GtkImage"
  "\" id=\"image1\"><property name=\"visible\">True</property><property na"
  "me=\"icon_name\">alacarte</property></object><object class=\"GtkSizeGro"
  "up\" id=\"sizegroup1\"/></interface>"
};

static const unsigned applicationsmenu_dialog_ui_length = 10869u;

