/* automatically generated from directorymenu-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (directorymenu_dialog_ui)
#endif
#ifdef __GNUC__
static const char directorymenu_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char directorymenu_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\"?><interface><requires lib=\"gtk+\" version=\"2.24"
  "\"/><object class=\"XfceTitledDialog\" id=\"dialog\"><property name=\"t"
  "itle\" translatable=\"yes\">Directory Menu</property><property name=\"i"
  "con_name\">gtk-properties</property><property name=\"type_hint\">normal"
  "</property><property name=\"has_separator\">False</property><child inte"
  "rnal-child=\"vbox\"><object class=\"GtkVBox\" id=\"dialog-vbox2\"><prop"
  "erty name=\"visible\">True</property><property name=\"orientation\">ver"
  "tical</property><property name=\"spacing\">2</property><child><object c"
  "lass=\"GtkVBox\" id=\"vbox1\"><property name=\"visible\">True</property"
  "><property name=\"border_width\">6</property><property name=\"orientati"
  "on\">vertical</property><property name=\"spacing\">6</property><child><"
  "object class=\"GtkFrame\" id=\"frame3\"><property name=\"visible\">True"
  "</property><property name=\"label_xalign\">0</property><property name=\""
  "shadow_type\">none</property><child><object class=\"GtkAlignment\" id=\""
  "alignment3\"><property name=\"visible\">True</property><property name=\""
  "left_padding\">12</property><child><object class=\"GtkTable\" id=\"tabl"
  "e1\"><property name=\"visible\">True</property><property name=\"border_"
  "width\">6</property><property name=\"n_rows\">2</property><property nam"
  "e=\"n_columns\">2</property><property name=\"column_spacing\">12</prope"
  "rty><property name=\"row_spacing\">6</property><child><object class=\"G"
  "tkFileChooserButton\" id=\"base-directory\"><property name=\"visible\">"
  "True</property><property name=\"local_only\">False</property><property "
  "name=\"action\">select-folder</property><property name=\"title\" transl"
  "atable=\"yes\">Select A Directory</property></object><packing><property"
  " name=\"left_attach\">1</property><property name=\"right_attach\">2</pr"
  "operty></packing></child><child><object class=\"GtkLabel\" id=\"label2\""
  "><property name=\"visible\">True</property><property name=\"xalign\">0<"
  "/property><property name=\"label\" translatable=\"yes\">_Base Directory"
  ":</property><property name=\"use_underline\">True</property><property n"
  "ame=\"mnemonic_widget\">base-directory</property></object><packing><pro"
  "perty name=\"x_options\">GTK_FILL</property></packing></child><child><o"
  "bject class=\"GtkLabel\" id=\"label4\"><property name=\"visible\">True<"
  "/property><property name=\"xalign\">0</property><property name=\"label\""
  " translatable=\"yes\">_Icon:</property><property name=\"use_underline\""
  ">True</property><property name=\"mnemonic_widget\">icon-button</propert"
  "y></object><packing><property name=\"top_attach\">1</property><property"
  " name=\"bottom_attach\">2</property><property name=\"x_options\">GTK_FI"
  "LL</property></packing></child><child><object class=\"GtkAlignment\" id"
  "=\"alignment2\"><property name=\"visible\">True</property><property nam"
  "e=\"xalign\">0</property><property name=\"xscale\">0</property><propert"
  "y name=\"yscale\">0</property><child><object class=\"GtkButton\" id=\"i"
  "con-button\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"receives_default\">True</pr"
  "operty></object></child></object><packing><property name=\"left_attach\""
  ">1</property><property name=\"right_attach\">2</property><property name"
  "=\"top_attach\">1</property><property name=\"bottom_attach\">2</propert"
  "y></packing></child></object></child></object></child><child type=\"lab"
  "el\"><object class=\"GtkLabel\" id=\"label1\"><property name=\"visible\""
  ">True</property><property name=\"label\" translatable=\"yes\">Appearanc"
  "e</property><attributes><attribute name=\"weight\" value=\"bold\"/></at"
  "tributes></object></child></object><packing><property name=\"expand\">F"
  "alse</property><property name=\"position\">0</property></packing></chil"
  "d><child><object class=\"GtkFrame\" id=\"frame1\"><property name=\"visi"
  "ble\">True</property><property name=\"label_xalign\">0</property><prope"
  "rty name=\"shadow_type\">none</property><child><object class=\"GtkAlign"
  "ment\" id=\"alignment1\"><property name=\"visible\">True</property><pro"
  "perty name=\"left_padding\">12</property><child><object class=\"GtkTabl"
  "e\" id=\"table2\"><property name=\"visible\">True</property><property n"
  "ame=\"border_width\">6</property><property name=\"n_rows\">2</property>"
  "<property name=\"n_columns\">2</property><property name=\"column_spacin"
  "g\">12</property><property name=\"row_spacing\">6</property><child><obj"
  "ect class=\"GtkEntry\" id=\"file-pattern\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">True</property><property nam"
  "e=\"tooltip_text\" translatable=\"yes\">Enter a list of patterns that w"
  "ill be used to determine which files are visible in a directory. If you"
  " specify more than one pattern here, the list items must be separated w"
  "ith semicolons (e.g. *.txt;*.doc).</property><property name=\"invisible"
  "_char\">&#x2022;</property></object><packing><property name=\"left_atta"
  "ch\">1</property><property name=\"right_attach\">2</property></packing>"
  "</child><child><object class=\"GtkLabel\" id=\"label7\"><property name="
  "\"visible\">True</property><property name=\"xalign\">0</property><prope"
  "rty name=\"label\" translatable=\"yes\">_File Pattern:</property><prope"
  "rty name=\"use_underline\">True</property><property name=\"mnemonic_wid"
  "get\">file-pattern</property></object><packing><property name=\"x_optio"
  "ns\">GTK_FILL</property></packing></child><child><object class=\"GtkChe"
  "ckButton\" id=\"hidden-files\"><property name=\"label\" translatable=\""
  "yes\">Show _hidden files</property><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">True</property><property name=\"rece"
  "ives_default\">False</property><property name=\"use_underline\">True</p"
  "roperty><property name=\"draw_indicator\">True</property></object><pack"
  "ing><property name=\"right_attach\">2</property><property name=\"top_at"
  "tach\">1</property><property name=\"bottom_attach\">2</property></packi"
  "ng></child></object></child></object></child><child type=\"label\"><obj"
  "ect class=\"GtkLabel\" id=\"label8\"><property name=\"visible\">True</p"
  "roperty><property name=\"label\" translatable=\"yes\">Filtering</proper"
  "ty><attributes><attribute name=\"weight\" value=\"bold\"/></attributes>"
  "</object></child></object><packing><property name=\"expand\">False</pro"
  "perty><property name=\"position\">1</property></packing></child></objec"
  "t><packing><property name=\"position\">1</property></packing></child><c"
  "hild internal-child=\"action_area\"><object class=\"GtkHButtonBox\" id="
  "\"dialog-action_area2\"><property name=\"visible\">True</property><prop"
  "erty name=\"layout_style\">end</property><child><object class=\"GtkButt"
  "on\" id=\"close-button\"><property name=\"label\">gtk-close</property><"
  "property name=\"visible\">True</property><property name=\"can_focus\">T"
  "rue</property><property name=\"receives_default\">True</property><prope"
  "rty name=\"use_stock\">True</property></object><packing><property name="
  "\"expand\">False</property><property name=\"fill\">False</property><pro"
  "perty name=\"position\">0</property></packing></child><child><object cl"
  "ass=\"GtkButton\" id=\"help-button\"><property name=\"label\">gtk-help<"
  "/property><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">True</property><property name=\"receives_default\">True</prop"
  "erty><property name=\"use_stock\">True</property></object><packing><pro"
  "perty name=\"expand\">False</property><property name=\"fill\">False</pr"
  "operty><property name=\"position\">1</property><property name=\"seconda"
  "ry\">True</property></packing></child></object><packing><property name="
  "\"expand\">False</property><property name=\"pack_type\">end</property><"
  "property name=\"position\">0</property></packing></child></object></chi"
  "ld><action-widgets><action-widget response=\"0\">close-button</action-w"
  "idget><action-widget response=\"0\">help-button</action-widget></action"
  "-widgets></object><object class=\"GtkSizeGroup\" id=\"sizegroup1\"><wid"
  "gets><widget name=\"label4\"/><widget name=\"label2\"/><widget name=\"l"
  "abel7\"/></widgets></object></interface>"
};

static const unsigned directorymenu_dialog_ui_length = 7555u;

